# fly.toml app configuration file generated for clarius-aegis on 2026-05-18T07:55:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clarius-aegis'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
