\section*{Our Family, Our Neighbourhood}

3MHEV02

\section*{2.1 People Around Us}

We live with our family. A family has elders and children. Grandmother,
grandfather, mother, father, sister and brother are our family members.

Our neighbours live near our house. The shopkeeper, the postman and the
doctor help us every day. We greet them with a smile.

\begin{figure}
\includegraphics[alt={},max width=\textwidth]{https://cdn.mathpix.com/cropped/acceptance-mh3-evs-01.jpg?height=400&width=600&top_left_y=300&top_left_x=100}
\captionsetup{labelformat=empty}
\caption{Fig. 1 - People who help us in our neighbourhood.}
\end{figure}

\section*{Try this.}

1. Say the names of your family members.
2. Who helps you when you are ill?

\section*{Exercise}

1. Draw your family in your notebook.
2. Name two people who help us in the neighbourhood.
3. Look at Fig. 1. Who do you see in the picture?
