"""Concept Map V2 — source-locked pipeline, prompt, validation, and renderer.

Replaces the multi-pass staged concept mapper with one master LLM call (+ optional
repair) and deterministic post-processing:

1. Topics locked to textbook/source headings (``expected_topics``).
2. Chapter tags and subject prefixes generated by code, not the model.
3. ``topic_display_name`` is exactly the topic name.
4. ``topic_concept_labels`` uses concept title, not display name.
5. Misconception appears once only.
6. Types/Cases structured first, then rendered into ``concept_description`` once.
7. Cases are sub-types under Types and must carry full source questions.
8. Examples/questions copied from source inventory — never shortened.
9. Chapter duration from finalized config, not the model.
10. English Literature uses the literature template and rejects pedagogy concepts.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable

from .concept_cleanup import neutralize_source_artifacts_preserve_images
from .mmd_figures import figure_markdown_index_from_mmd, inline_figures_in_text

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

SUBJECT_CODE: dict[str, str] = {
    "mathematics": "MA",
    "physics": "PH",
    "chemistry": "CH",
    "biology": "BI",
    "science": "SC",
    "geography": "SS",
    "history": "SS",
    "civics": "SS",
    "economics": "SS",
    "political science": "SS",
    "social science": "SS",
    "english": "EL",
    "english literature": "EL",
}

SUBJECT_DISPLAY: dict[str, str] = {
    "mathematics": "Mathematics",
    "physics": "Physics",
    "chemistry": "Chemistry",
    "biology": "Biology",
    "science": "Science",
    "geography": "Social_Science",
    "history": "Social_Science",
    "civics": "Social_Science",
    "economics": "Social_Science",
    "political science": "Social_Science",
    "social science": "Social_Science",
    "english": "English_Literature",
    "english literature": "English_Literature",
}

ENGLISH_LIT_BANNED_CONCEPT_TERMS = [
    "pre-reading",
    "prediction",
    "discussion",
    "reading in manageable parts",
    "oral checks",
    "informal letter writing",
    "family news",
    "lesson plan",
    "teacher activity",
    "classroom activity",
    "pedagogy",
    "worksheet creation",
]

DEFAULT_ENGLISH_LIT_TEMPLATE = [
    "Text Context and Genre",
    "Plot Sequence and Conflict",
    "Character Motivation and Response",
    "Themes, Values and Message",
    "Language, Tone and Literary Devices",
    "Key Extract Interpretation",
    "Vocabulary and Expressions in Context",
    "Answer Framing for Text-Based Questions",
]

_SOURCE_ARTIFACT_RE = re.compile(
    r"\b(example|ex\.?|exercise|activity|activities|fig\.?|figure|table|page|mmd|mmds)\s*\d+",
    re.IGNORECASE,
)

# Figure references in case prompts → inline markdown from chapter MMD when available.
_FIG_REF_INLINE_RE = re.compile(
    r"\b(Fig(?:ure)?\.?\s*(\d+(?:\.\d+)*))",
    re.IGNORECASE,
)
_MARKDOWN_IMG_ANY_RE = re.compile(
    r"!\[([^\]]*)\]\(([^)]+)\)",
    re.IGNORECASE,
)

_GENERIC_MISCONCEPTIONS = [
    "students may get confused",
    "learners may misunderstand the concept",
    "students may not understand",
    "students may confuse this with other concepts",
]


# --------------------------------------------------------------------------- #
# Data classes
# --------------------------------------------------------------------------- #

@dataclass
class RunConfig:
    board: str
    class_num: int
    subject: str
    chapter: str
    publication: str
    chapter_duration_minutes: int
    expected_topics: list[str]
    allow_introduction_topic: bool = False
    english_literature_template_concepts: list[str] | None = None


@dataclass
class MinedCase:
    case_id: str
    source_question_id: str
    case_prompt: str
    case_signature: str = ""


@dataclass
class MinedType:
    type_id: str
    type_title: str
    type_description: str = ""
    task_pattern: str = ""
    topic_hint: str = ""
    concept_match_hint: str = ""
    source_question_ids: list[str] = field(default_factory=list)
    cases: list[MinedCase] = field(default_factory=list)


@dataclass
class ConceptCore:
    concept_id: str
    topic: str
    parent_concept: str
    concept_title: str
    description_body: str
    mastery: str
    keywords: list[str]
    source_evidence: list[str] = field(default_factory=list)
    misconception: str | None = None


@dataclass
class ConceptWithTypes(ConceptCore):
    types: list[MinedType] = field(default_factory=list)
    is_culmination: bool = False


# Alias for coverage/culmination helpers (matches workbook row shape).
ConceptRow = ConceptWithTypes


# --------------------------------------------------------------------------- #
# String / tag helpers (code-owned — never LLM)
# --------------------------------------------------------------------------- #

def norm(s: str) -> str:
    return re.sub(r"\s+", " ", str(s or "")).strip()


def slug(s: str) -> str:
    return re.sub(r"^_+|_+$", "",
                  re.sub(r"[^A-Za-z0-9]+", "_",
                         norm(s).replace("'", "").replace("'", "")))


def strip_numbering(s: str) -> str:
    out = norm(s)
    out = re.sub(
        r"^(chapter|unit|topic|section|exercise|ex)\s*\d+([.\-:]\d+)*\s*[:.)-]?\s*",
        "", out, flags=re.IGNORECASE)
    out = re.sub(r"^\d+([.\-:]\d+)*\s*[:.)-]?\s*", "", out)
    return out.strip()


def subject_code(subject: str) -> str:
    key = subject.lower().strip()
    return SUBJECT_CODE.get(key) or slug(subject)[:2].upper()


def subject_display(subject: str) -> str:
    key = subject.lower().strip()
    return SUBJECT_DISPLAY.get(key) or slug(subject)


def board_code(board: str) -> str:
    return board.upper().strip()


def class_code(class_num: int) -> str:
    return str(class_num).zfill(2)


def concept_prefix(cfg: RunConfig) -> str:
    return f"{class_code(cfg.class_num)}{board_code(cfg.board)[:2]}{subject_code(cfg.subject)}"


def chapter_tag(cfg: RunConfig) -> str:
    return (
        f"{class_code(cfg.class_num)}_{subject_display(cfg.subject)}_"
        f"{board_code(cfg.board)}_{slug(cfg.publication)}"
    )


def topic_display_name(topic: str) -> str:
    return strip_numbering(topic)


def topic_tag(cfg: RunConfig, topic: str, stage: str = "PL") -> str:
    return f"{concept_prefix(cfg)}_{slug(cfg.chapter)}_{stage}_{slug(topic_display_name(topic))}"


def concept_tag(cfg: RunConfig, concept: ConceptCore, stage: str = "PL") -> str:
    return f"{concept_prefix(cfg)}_{slug(cfg.chapter)}_{stage}_{slug(concept.concept_title)}"


def topic_concept_labels(concepts: list[ConceptCore]) -> str:
    return ", ".join(c.concept_title for c in concepts)


def is_english_literature(cfg: RunConfig) -> bool:
    return cfg.subject.lower().strip() in {"english", "english literature"}


def assert_finalized_config(cfg: RunConfig) -> None:
    if not cfg.publication:
        raise ValueError(
            "Missing publication. Chapter tag must include publication.")
    if not cfg.chapter_duration_minutes or cfg.chapter_duration_minutes <= 0:
        raise ValueError(
            "Missing finalized chapter duration. Do not let the LLM estimate this.")
    if not cfg.expected_topics:
        raise ValueError(
            "Missing expected_topics. Lock topics from textbook TOC/source "
            "headings before concept extraction.")


def canonical_topics(cfg: RunConfig) -> list[str]:
    topics = [topic_display_name(t) for t in cfg.expected_topics if topic_display_name(t)]
    if not cfg.allow_introduction_topic:
        topics = [t for t in topics if not re.match(r"^(introduction|overview)$", t, re.I)]
    if is_english_literature(cfg):
        topics = [cfg.chapter]
    seen: set[str] = set()
    out: list[str] = []
    for t in topics:
        key = t.lower()
        if key not in seen:
            seen.add(key)
            out.append(t)
    return out


def parse_duration_minutes(text: str) -> int | None:
    m = re.search(r"(\d+)", text or "")
    return int(m.group(1)) if m else None


def run_config_from_meta(
    *,
    board: str = "",
    grade: str = "",
    subject: str = "",
    chapter_title: str = "",
    publication: str = "",
    chapter_duration: str = "",
    expected_topics: list[str],
    allow_introduction_topic: bool | None = None,
) -> RunConfig:
    """Build a :class:`RunConfig` from chapter/upload metadata."""
    class_num = 10
    m = re.search(r"\d+", grade or "")
    if m:
        class_num = int(m.group())
    duration = parse_duration_minutes(chapter_duration)
    if not duration:
        # Deterministic fallback: ~60 minutes per locked topic, bounded.
        n = max(len(expected_topics), 1)
        duration = max(180, min(720, n * 60))
    if allow_introduction_topic is None:
        allow_introduction_topic = any(
            re.match(r"^introduction$", topic_display_name(t), re.I)
            for t in expected_topics
        )
    pub = norm(publication) or "NCERT"
    return RunConfig(
        board=board or "CBSE",
        class_num=class_num,
        subject=subject or "General",
        chapter=chapter_title or "Chapter",
        publication=pub,
        chapter_duration_minutes=duration,
        expected_topics=expected_topics,
        allow_introduction_topic=allow_introduction_topic,
    )


def has_source_artifact(text: str) -> bool:
    return bool(_SOURCE_ARTIFACT_RE.search(text or ""))


def sanitize_case_prompt(prompt: str, *, chapter_text: str = "") -> str:
    """Rewrite source-artifact labels; inline figure images from chapter MMD."""
    p = norm(prompt)
    if not p:
        return p
    fig_index = figure_markdown_index_from_mmd(chapter_text)
    p = inline_figures_in_text(p, fig_index)
    p = neutralize_source_artifacts_preserve_images(p)
    return clean_one_line(p)


def sanitize_concept_cases(
    concepts: list[ConceptWithTypes],
    *,
    chapter_text: str = "",
) -> list[ConceptWithTypes]:
    """Deterministically clean all case prompts before validation."""
    for concept in concepts:
        for type_ in concept.types:
            for case in type_.cases:
                case.case_prompt = sanitize_case_prompt(
                    case.case_prompt, chapter_text=chapter_text,
                )
    return concepts


def clean_one_line(s: str) -> str:
    out = norm(s).replace("MMDs", "chapter").replace("MMD", "chapter")
    # Protect URLs before normalizing section separators (avoid breaking https://).
    urls: list[str] = []

    def _stash_url(match: re.Match[str]) -> str:
        urls.append(match.group(0))
        return f"__URL_{len(urls) - 1}__"

    out = re.sub(r"https?://\S+", _stash_url, out)
    out = re.sub(r"\s*//\s*", " // ", out)
    for i, url in enumerate(urls):
        out = out.replace(f"__URL_{i}__", url)
    return out.strip()


def sanitize_description_body(s: str) -> str:
    """Strip pre-rendered section labels so rendering never duplicates blocks."""
    out = str(s or "")
    out = re.sub(r"^Description:\s*", "", out, flags=re.I)
    out = re.sub(r"\s*//\s*Types:\s*.*$", "", out, flags=re.I | re.S)
    out = re.sub(r"\s*//\s*Misconceptions?:\s*.*$", "", out, flags=re.I | re.S)
    out = re.sub(r"\n?Achieving Mastery:\s*.*$", "", out, flags=re.I | re.S)
    out = re.sub(r"\s*//\s*Achieving Mastery:\s*.*$", "", out, flags=re.I | re.S)
    out = clean_one_line(out.strip())
    if not out:
        raise ValueError("Empty description_body after sanitization.")
    return out


def sanitize_mastery(s: str) -> str:
    out = re.sub(r"^Achieving Mastery:\s*", "", str(s or ""), flags=re.I).strip()
    out = clean_one_line(out)
    if not out:
        raise ValueError("Missing Achieving Mastery line.")
    return re.sub(r"[.]*$", ".", out)


def sanitize_misconception(s: str | None) -> str | None:
    if not s:
        return None
    out = re.sub(r"^Misconceptions?:\s*", "", str(s), flags=re.I)
    out = re.sub(r"\b(n/a|none|not applicable)\b", "", out, flags=re.I).strip()
    out = clean_one_line(out)
    if not out:
        return None
    if any(bad in out.lower() for bad in _GENERIC_MISCONCEPTIONS):
        return None
    return re.sub(r"[.]*$", ".", out)


def case_prompt_is_valid(prompt: str) -> bool:
    p = norm(prompt)
    if not p or len(p) < 20:
        return False
    # Alt text in inlined figure images may retain Fig. N labels — ignore those.
    stripped = re.sub(r"!\[[^\]]*\]\([^)]+\)", "[figure]", p)
    return not has_source_artifact(stripped)


def render_types(types: list[MinedType]) -> str:
    rendered: list[str] = []
    for type_ in types:
        valid_cases = [c for c in type_.cases if case_prompt_is_valid(c.case_prompt)]
        if not valid_cases:
            continue
        case_text = " ".join(
            f"Case {str(i + 1).zfill(2)}: {clean_one_line(c.case_prompt)}"
            for i, c in enumerate(valid_cases)
        )
        rendered.append(
            f"Type {str(len(rendered) + 1).zfill(2)}: "
            f"{clean_one_line(type_.type_title)} {case_text}"
        )
    return " ".join(rendered)


def render_concept_description(concept: ConceptWithTypes) -> str:
    body = sanitize_description_body(concept.description_body)
    mastery = sanitize_mastery(concept.mastery)
    misconception = sanitize_misconception(concept.misconception)
    types_text = render_types(concept.types or [])
    sections = [
        f"Description: {body}\nAchieving Mastery: {mastery}",
        f"Misconception: {misconception}" if misconception else None,
        f"Types: {types_text}" if types_text else None,
    ]
    return " // ".join(s for s in sections if s)


# --------------------------------------------------------------------------- #
# Topic coverage + culmination helpers (deterministic, code-enforced)
# --------------------------------------------------------------------------- #

def normalize_topic_name(topic: str) -> str:
    out = str(topic or "")
    out = re.sub(
        r"^(topic|section|chapter)\s*\d+\s*[:.)-]?\s*", "", out, flags=re.IGNORECASE)
    out = re.sub(r"^\d+(\.\d+)*\s*[:.)-]?\s*", "", out)
    return re.sub(r"\s+", " ", out).strip()


def topic_key(topic: str) -> str:
    return normalize_topic_name(topic).lower()


def is_culmination_row(row: ConceptRow) -> bool:
    return (
        row.is_culmination is True
        or (row.parent_concept or "").lower() == "culmination"
        or (row.concept_title or "").lower().startswith("culmination -")
    )


def strip_model_culmination_rows(rows: list[ConceptRow]) -> list[ConceptRow]:
    """Remove LLM-authored culmination rows before coverage validation."""
    return [r for r in rows if not is_culmination_row(r)]


def validate_locked_topic_coverage(
    *,
    locked_topics: list[str],
    rows: list[ConceptRow],
    min_normal_concepts_per_topic: int = 1,
) -> list[str]:
    errors: list[str] = []
    normal_rows = [r for r in rows if not is_culmination_row(r)]

    for locked_topic in locked_topics:
        count = sum(
            1 for r in normal_rows
            if topic_key(r.topic) == topic_key(locked_topic)
        )
        if count < min_normal_concepts_per_topic:
            errors.append(
                f'missing_topic_concepts: "{locked_topic}" has {count} normal '
                f"concept(s), expected at least {min_normal_concepts_per_topic}."
            )

    illegal_topics = sorted({
        normalize_topic_name(r.topic)
        for r in rows
        if normalize_topic_name(r.topic)
        and not any(
            topic_key(locked) == topic_key(r.topic) for locked in locked_topics
        )
    })
    for topic in illegal_topics:
        errors.append(f'illegal_topic: "{topic}" is not in lockedTopics.')

    return errors


_TOPIC_STOPWORDS = frozenset({
    "a", "an", "the", "and", "or", "of", "in", "on", "to", "for", "with",
    "by", "from", "at", "is", "are", "as", "its", "their", "this", "that",
})


def topic_tokens(topic: str) -> set[str]:
    return {
        t for t in re.split(r"[^a-z0-9]+", topic_key(topic))
        if t and t not in _TOPIC_STOPWORDS
    }


def topic_match_score(a: str, b: str) -> float:
    """Token overlap score in [0, 1] for fuzzy topic/title matching."""
    ta, tb = topic_tokens(a), topic_tokens(b)
    if not ta or not tb:
        return 0.0
    if topic_key(a) == topic_key(b):
        return 1.0
    if topic_key(a) in topic_key(b) or topic_key(b) in topic_key(a):
        return 0.9
    overlap = ta & tb
    if not overlap:
        return 0.0
    score = len(overlap) / max(len(ta), len(tb))
    if overlap & {"series", "parallel", "resistance", "current", "ohm", "circuit"}:
        score = max(score, len(overlap) / min(len(ta), len(tb)))
    return min(score, 1.0)


def resolve_locked_topic(candidate: str, locked_topics: list[str]) -> str | None:
    """Map a free-text topic to the best matching locked topic, if any."""
    if not candidate or not locked_topics:
        return None
    best: tuple[float, str] | None = None
    for locked in locked_topics:
        score = topic_match_score(candidate, locked)
        if score >= 0.5 and (best is None or score > best[0]):
            best = (score, locked)
    return best[1] if best else None


def topics_missing_coverage(
    locked_topics: list[str],
    rows: list[ConceptRow],
    *,
    min_normal_concepts_per_topic: int = 1,
) -> list[str]:
    missing: list[str] = []
    for locked_topic in locked_topics:
        count = sum(
            1 for r in rows
            if not is_culmination_row(r)
            and topic_key(r.topic) == topic_key(locked_topic)
        )
        if count < min_normal_concepts_per_topic:
            missing.append(locked_topic)
    return missing


def snap_rows_to_locked_topics(
    rows: list[ConceptRow], locked_topics: list[str],
) -> tuple[list[ConceptRow], int]:
    """Normalize row.topic to canonical locked topic names when clearly matching."""
    snapped = 0
    locked_by_key = {topic_key(t): normalize_topic_name(t) for t in locked_topics}
    for row in rows:
        if is_culmination_row(row):
            continue
        key = topic_key(row.topic)
        if key in locked_by_key:
            canonical = locked_by_key[key]
            if row.topic != canonical:
                row.topic = canonical
                snapped += 1
            continue
        resolved = resolve_locked_topic(row.topic, locked_topics)
        if resolved:
            canonical = locked_by_key[topic_key(resolved)]
            if row.topic != canonical:
                row.topic = canonical
                snapped += 1
    return rows, snapped


def reassign_misplaced_concepts(
    rows: list[ConceptRow], locked_topics: list[str],
) -> tuple[list[ConceptRow], int]:
    """Move concepts whose titles clearly belong to uncovered locked topics."""
    reassigned = 0
    used: set[int] = set()
    for missing_topic in topics_missing_coverage(locked_topics, rows):
        best_row: ConceptRow | None = None
        best_score = 0.0
        for row in rows:
            if is_culmination_row(row) or id(row) in used:
                continue
            if topic_key(row.topic) == topic_key(missing_topic):
                continue
            score = max(
                topic_match_score(row.concept_title, missing_topic),
                topic_match_score(row.topic, missing_topic),
            )
            if score > best_score:
                best_score = score
                best_row = row
        if best_row and best_score >= 0.5:
            best_row.topic = normalize_topic_name(missing_topic)
            used.add(id(best_row))
            reassigned += 1
    return rows, reassigned


def extract_topic_section(
    chapter_text: str, topic: str, locked_topics: list[str],
) -> str:
    """Pull source text for one locked topic from markdown headings."""
    topic_norm = topic_key(topic)
    lines = (chapter_text or "").splitlines()
    collecting = False
    parts: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#"):
            heading = normalize_topic_name(stripped.lstrip("#").strip())
            if collecting:
                break
            if (
                topic_key(heading) == topic_norm
                or topic_match_score(heading, topic) >= 0.6
            ):
                collecting = True
            continue
        if collecting and stripped:
            parts.append(stripped)

    if parts:
        return "\n".join(parts)[:2500]

    pattern = re.compile(re.escape(normalize_topic_name(topic)), re.IGNORECASE)
    match = pattern.search(chapter_text or "")
    if match:
        start = max(0, match.start() - 200)
        end = min(len(chapter_text), match.end() + 1800)
        return (chapter_text or "")[start:end].strip()

    return ""


def inventory_for_topic(inventory: list[dict], topic: str) -> list[dict]:
    matched: list[tuple[float, dict]] = []
    for item in inventory:
        if not isinstance(item, dict):
            continue
        hint = str(item.get("topic_hint") or "")
        score = max(
            topic_match_score(hint, topic),
            topic_match_score(str(item.get("raw_task") or ""), topic),
        )
        if score >= 0.4:
            matched.append((score, item))
    matched.sort(key=lambda x: x[0], reverse=True)
    return [item for _, item in matched]


def build_missing_topic_fill_prompt(
    *,
    missing_topics: list[str],
    current_rows: list[ConceptRow],
    chapter_text: str,
    question_inventory: list[dict],
    locked_topics: list[str],
) -> str:
    import json
    topic_sections = [
        f"### {topic}\n{extract_topic_section(chapter_text, topic, locked_topics) or '(section not found)'}"
        for topic in missing_topics
    ]
    relevant_inventory = []
    for topic in missing_topics:
        relevant_inventory.extend(inventory_for_topic(question_inventory, topic))
    return f"""
You are adding missing concepts to a school concept map.

Return ONLY strict JSON:
{{
  "concepts": [
    {{
      "concept_id": "",
      "topic": "",
      "parent_concept": "",
      "concept_title": "",
      "description_body": "",
      "mastery": "",
      "misconception": "",
      "keywords": [],
      "source_evidence": [],
      "types": []
    }}
  ]
}}

MISSING LOCKED TOPICS — add exactly one NEW normal concept for EACH topic below:
{chr(10).join(f"{i + 1}. {t}" for i, t in enumerate(missing_topics))}

RULES:
- Return ONLY the new concepts for the missing topics listed above.
- Do NOT return any existing concepts.
- topic must exactly match the missing locked topic name.
- Use source-backed description_body and mastery from that topic's chapter section.
- Add Types/Cases only when source-backed assessable tasks exist in the inventory.
- Do not create culmination rows.
- Do not write source labels such as Example 3, Exercise 1.2, Fig 6.4, Table 1, or page numbers.
- Every listed missing topic MUST appear in your response with at least one concept.

EXISTING CONCEPTS (for context only — do not return these):
{json.dumps([_concept_to_dict(c) for c in current_rows if not is_culmination_row(c)], ensure_ascii=False, indent=2)}

SOURCE SECTIONS FOR MISSING TOPICS:
{chr(10).join(topic_sections)}

RELEVANT QUESTION / TASK INVENTORY:
{json.dumps(_slim_inventory(relevant_inventory), ensure_ascii=False, indent=2)}

FULL CHAPTER SOURCE:
{chapter_text}
""".strip()


def build_single_topic_fill_prompt(
    *,
    topic: str,
    current_rows: list[ConceptRow],
    chapter_text: str,
    question_inventory: list[dict],
    locked_topics: list[str],
) -> str:
    import json
    section = extract_topic_section(chapter_text, topic, locked_topics)
    inv_items = inventory_for_topic(question_inventory, topic)
    return f"""
You are adding one missing concept for a locked textbook topic.

Return ONLY strict JSON:
{{
  "concepts": [
    {{
      "concept_id": "",
      "topic": "{normalize_topic_name(topic)}",
      "parent_concept": "",
      "concept_title": "",
      "description_body": "",
      "mastery": "",
      "misconception": "",
      "keywords": [],
      "source_evidence": [],
      "types": []
    }}
  ]
}}

MISSING LOCKED TOPIC:
{normalize_topic_name(topic)}

RULES:
- Return exactly one durable normal concept for this topic only.
- topic must be exactly "{normalize_topic_name(topic)}".
- Use vocabulary and ideas from the source section below.
- Add Types/Cases only when source-backed assessable tasks exist.
- Do not create culmination rows.
- Do not write source labels such as Example 3, Exercise 1.2, Fig 6.4, Table 1, or page numbers.

EXISTING CONCEPTS (do not return these):
{json.dumps([_concept_to_dict(c) for c in current_rows if not is_culmination_row(c)], ensure_ascii=False, indent=2)}

SOURCE SECTION:
{section or "(section not found — use full chapter source below)"}

RELEVANT QUESTION / TASK INVENTORY:
{json.dumps(_slim_inventory(inv_items), ensure_ascii=False, indent=2)}

FULL CHAPTER SOURCE:
{chapter_text}
""".strip()


def merge_new_concept_rows(
    existing: list[ConceptRow], new_rows: list[ConceptRow],
) -> list[ConceptRow]:
    """Append only novel normal concepts; never drop existing rows."""
    out = list(existing)
    seen = {
        (topic_key(r.topic), slug(r.concept_title).lower())
        for r in existing if not is_culmination_row(r)
    }
    for row in new_rows:
        if is_culmination_row(row):
            continue
        key = (topic_key(row.topic), slug(row.concept_title).lower())
        if key in seen:
            continue
        seen.add(key)
        out.append(row)
    return out


def short_concept_name(name: str) -> str:
    return re.sub(r"\s+", " ", re.sub(
        r"^Culmination\s*-\s*", "", str(name or ""), flags=re.IGNORECASE)).strip()


def build_culmination_title(topic_concepts: list[ConceptRow]) -> str:
    names = [
        short_concept_name(c.concept_title)
        for c in topic_concepts
        if not is_culmination_row(c) and short_concept_name(c.concept_title)
    ][:4]

    if not names:
        return "Culmination - Topic Recap"
    if len(names) == 1:
        return f"Culmination - {names[0]}"
    if len(names) == 2:
        return f"Culmination - {names[0]} and {names[1]}"
    return (
        f"Culmination - {', '.join(names[:-1])} and {names[-1]}"
    )


def make_culmination_row(
    topic: str, topic_concepts: list[ConceptRow], index: int,
) -> ConceptRow:
    topic_name = normalize_topic_name(topic)
    return ConceptWithTypes(
        concept_id=f"CULMINATION-{index + 1:04d}",
        topic=topic_name,
        parent_concept="Culmination",
        concept_title=build_culmination_title(topic_concepts),
        description_body="Recap",
        mastery=(
            f"Connecting the key ideas of {topic_name} to solve mixed "
            "questions from the section."
        ),
        misconception=None,
        keywords=["recap", "mixed application", "section review"],
        source_evidence=[],
        types=[],
        is_culmination=True,
    )


def ensure_exactly_one_culmination_per_locked_topic(
    *,
    locked_topics: list[str],
    rows: list[ConceptRow],
) -> list[ConceptRow]:
    normal_rows = [r for r in rows if not is_culmination_row(r)]
    final_rows: list[ConceptRow] = []

    for index, locked_topic in enumerate(locked_topics):
        topic_concepts = [
            r for r in normal_rows
            if topic_key(r.topic) == topic_key(locked_topic)
        ]
        final_rows.extend(topic_concepts)
        final_rows.append(make_culmination_row(locked_topic, topic_concepts, index))

    return final_rows


def validate_pre_deposit(
    *,
    locked_topics: list[str],
    rows: list[ConceptRow],
) -> list[str]:
    errors: list[str] = []

    for locked_topic in locked_topics:
        normal_count = sum(
            1 for r in rows
            if topic_key(r.topic) == topic_key(locked_topic)
            and not is_culmination_row(r)
        )
        culmination_count = sum(
            1 for r in rows
            if topic_key(r.topic) == topic_key(locked_topic)
            and is_culmination_row(r)
        )

        if normal_count < 1:
            errors.append(
                f'predeposit_missing_topic_concepts: "{locked_topic}" has no '
                "normal concepts."
            )
        if culmination_count != 1:
            errors.append(
                f'predeposit_culmination_count: "{locked_topic}" has '
                f"{culmination_count} culmination row(s), expected exactly 1."
            )

    return errors


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #

def validate_concept_map(cfg: RunConfig, concepts: list[ConceptWithTypes]) -> list[str]:
    errors: list[str] = []
    topics = canonical_topics(cfg)
    allowed = {t.lower() for t in topics}
    seen_concepts: dict[str, str] = {}
    seen_type_assignments: dict[str, str] = {}
    seen_source_questions: dict[str, str] = {}

    for c in concepts:
        if is_culmination_row(c):
            continue
        topic = topic_display_name(c.topic)
        if topic.lower() not in allowed:
            errors.append(
                f'Invalid topic "{c.topic}". Must be one of: {" | ".join(topics)}')
        if (re.match(r"^(overview|introduction)$", topic, re.I)
                and not cfg.allow_introduction_topic
                and not is_english_literature(cfg)):
            errors.append(
                f'Unwanted topic "{topic}". Do not create Overview/Introduction '
                "unless source requires it.")

        if is_english_literature(cfg):
            title_l = c.concept_title.lower()
            bad = next((t for t in ENGLISH_LIT_BANNED_CONCEPT_TERMS if t in title_l), None)
            if bad:
                errors.append(
                    f'English Literature concept "{c.concept_title}" is invalid '
                    f"pedagogy/activity content: {bad}")

        key = slug(c.concept_title).lower()
        if key in seen_concepts:
            errors.append(
                f'Duplicate concept "{c.concept_title}" appears in both '
                f'"{seen_concepts[key]}" and "{topic}".')
        else:
            seen_concepts[key] = topic

        if len(re.findall(r"Misconceptions?:", c.misconception or "", re.I)) > 1:
            errors.append(f'Duplicate Misconception section in "{c.concept_title}".')
        if c.misconception and not sanitize_misconception(c.misconception):
            errors.append(f'Generic or invalid misconception in "{c.concept_title}".')

        for t in c.types or []:
            if not t.cases:
                errors.append(
                    f'Type "{t.type_title}" under "{c.concept_title}" has no '
                    "source-backed Cases.")
            if t.type_id in seen_type_assignments:
                errors.append(
                    f"Type {t.type_id} assigned to more than one concept: "
                    f'"{seen_type_assignments[t.type_id]}" and "{c.concept_title}".')
            else:
                seen_type_assignments[t.type_id] = c.concept_title
            for qid in t.source_question_ids or []:
                if qid in seen_source_questions:
                    errors.append(
                        f"Question {qid} assigned to multiple concepts: "
                        f'"{seen_source_questions[qid]}" and "{c.concept_title}".')
                else:
                    seen_source_questions[qid] = c.concept_title
            for cs in t.cases or []:
                if not case_prompt_is_valid(cs.case_prompt):
                    errors.append(
                        f'Invalid/short/source-artifact Case in "{c.concept_title}" > '
                        f'"{t.type_title}": "{cs.case_prompt}"')
    return errors


# --------------------------------------------------------------------------- #
# Prompts
# --------------------------------------------------------------------------- #

def _slim_inventory(items: list[dict]) -> list[dict]:
    """Pass only fields the V2 master prompt needs."""
    out: list[dict] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        out.append({
            "qid": item.get("qid", ""),
            "source_kind": item.get("source_kind", "other"),
            "source_label": item.get("source_label", ""),
            "topic_hint": item.get("topic_hint", ""),
            "raw_task": item.get("raw_task", ""),
            "normalized_task": item.get("normalized_task", ""),
            "raw_solution_or_answer": item.get("raw_solution_or_answer", ""),
            "shared_context": item.get("shared_context", ""),
            "subpart_label": item.get("subpart_label", ""),
            "order_index": item.get("order_index", 0),
        })
    return out


def build_concept_map_prompt(
    cfg: RunConfig, chapter_text: str, inventory: list[dict],
) -> str:
    assert_finalized_config(cfg)
    topics = canonical_topics(cfg)
    template = (
        cfg.english_literature_template_concepts or DEFAULT_ENGLISH_LIT_TEMPLATE
    )
    import json
    inv_json = json.dumps(_slim_inventory(inventory), ensure_ascii=False, indent=2)
    topic_lines = "\n".join(f"  {i + 1}. {t}" for i, t in enumerate(topics))
    template_lines = "\n".join(f"  {i + 1}. {x}" for i, x in enumerate(template))

    return f"""
You are a strict source-grounded concept mapping engine for school curriculum.

Return ONLY strict JSON:
{{
  "concepts": [
    {{
      "concept_id": "CONCEPT-0001",
      "topic": "",
      "parent_concept": "",
      "concept_title": "",
      "description_body": "",
      "mastery": "",
      "misconception": "",
      "keywords": [],
      "source_evidence": [],
      "types": [
        {{
          "type_id": "TYPE-0001",
          "type_title": "",
          "type_description": "",
          "task_pattern": "",
          "topic_hint": "",
          "concept_match_hint": "",
          "source_question_ids": ["QINV-0001"],
          "cases": [
            {{
              "case_id": "CASE-0001",
              "source_question_id": "QINV-0001",
              "case_prompt": "",
              "case_signature": ""
            }}
          ]
        }}
      ]
    }}
  ],
  "audit": {{
    "chapter_tag": "{chapter_tag(cfg)}",
    "chapter_duration_minutes": {cfg.chapter_duration_minutes},
    "topic_count": {len(topics)},
    "coverage_notes": []
  }}
}}

NON-NEGOTIABLE RUN CONTEXT:
- Board: {cfg.board}
- Class: {cfg.class_num}
- Subject: {cfg.subject}
- Chapter: {cfg.chapter}
- Publication: {cfg.publication}
- Chapter tag must be exactly: {chapter_tag(cfg)}
- Chapter duration must be exactly: {cfg.chapter_duration_minutes}
- Allowed topics, in exact reading order:
{topic_lines}

TOPIC RULES:
- Use ONLY the allowed topics above.
- topic must exactly match one allowed topic.
- Do not create Overview, Introduction, Miscellaneous, Practice, Exercise, Examples, or Activity topics unless they are explicitly present in the allowed topic list.
- Do not duplicate a concept across two topics.
- BPT, CBPT, theorem variants, formulas, events, characters, processes, or definitions belong only to the topic where the source teaches them most directly.
- If a later topic reuses an earlier concept, do not create it again. Mention reuse only inside the relevant Type/Case when needed.

CONCEPT RULES:
- A concept is a durable teachable mastery objective.
- Do not create rows for cases, examples, individual questions, generic activities, or teacher methods.
- concept_title must be the title name only. No display prefix, no topic number, no chapter number.
- Use textbook/source vocabulary.
- Avoid repeated sibling openers.
- parent_concept must be a compact cluster name, not a duplicate of topic.
- keywords: 3 to 6 lowercase keywords.

DESCRIPTION RULES:
- description_body must contain only the teachable explanation.
- Do not include "Description:", "Types:", "Case:", "Misconception:", or "Achieving Mastery:" inside description_body.
- 45 to 90 words unless the concept is very simple.
- Keep the scope of the concept tight. Do not pull types/cases/details from the next concept.
- mastery must be one short sentence saying what the learner can do after mastering this concept.
- misconception must appear at most once and must be specific.
- Do not write generic misconceptions.
- Do not write N/A, None, Not applicable, filler, or placeholders.

TYPES AND CASES:
- Types classify assessable question/task varieties under that exact concept.
- Cases are sub-types/examples under Types.
- If no source-backed Case exists for a Type, do not list that Type.
- If a concept has no meaningful assessable source task, use an empty types array.
- Every Case must be copied from the source question/task inventory as a full teacher-executable prompt.
- Do not shorten questions.
- Preserve all numbers, expressions, diagrams/tables/passages context, names, dates, givens, conditions, quotations, and exact asks.
- Do not write "Example 3", "Exercise 1.2", "Fig 6.4", "Table 1", page references, or source labels in case_prompt.
- Substitute the actual content instead.
- Include as many source examples as available for each Type.
- Every inventory item must be assigned to exactly one concept unless it is truly rhetorical/non-assessable.
- Do not assign one question/task to multiple concepts.

TOPIC COVERAGE:
- You are given locked textbook topics in reading order.
- Every locked topic must receive at least one normal concept unless the source text for that topic is completely absent.
- Do not create topics outside the locked topic list.
- Do not collapse several textbook topics into one concept.
- Do not duplicate the same concept across two topics.
- Do not create culmination rows. Culmination rows are generated by code after validation.

CONCEPT COUNT:
- Do not target a fixed number of concepts.
- Do not equalize concept counts across topics.
- A narrow topic may have one durable concept.
- A dense topic may have several durable concepts.
- Do not create filler concepts to satisfy a count.

SUBJECT-SPECIFIC RULES:
- Mathematics: Types may be numerical, proof, construction, graph, theorem application, formula, diagram, reasoning, or word-problem patterns.
- Science: Types may be diagram, experiment, observation, inference, process, comparison, numerical, reasoning, or application patterns.
- Social Science: Types may be definition, cause-effect, comparison, chronology, map, source, case, data, evidence, or long-answer patterns.
- English Literature: topic must be exactly the prose/poem/drama name "{cfg.chapter}".
- English Literature must follow this concept family unless a source-specific idea clearly requires a tighter concept:
{template_lines}
- English Literature must NOT create pedagogy/activity concepts such as pre-reading prediction, oral checks, reading in parts, informal letter writing, family news, classroom discussion, or lesson planning unless the chapter itself assesses it as text content.

OUTPUT SAFETY:
- Return JSON only.
- No markdown.
- No commentary.
- No source-artifact labels.
- Never use the words MMD or MMDs.

QUESTION / TASK INVENTORY:
{inv_json}

CHAPTER SOURCE:
{chapter_text}
""".strip()


def build_strict_repair_prompt(
    *,
    locked_topics: list[str],
    current_rows: list[ConceptRow],
    validation_errors: list[str],
    chapter_text: str,
    question_inventory: list[dict],
) -> str:
    import json
    return f"""
You are repairing a school concept map.

Return ONLY strict JSON:
{{
  "concepts": [
    {{
      "concept_id": "",
      "topic": "",
      "parent_concept": "",
      "concept_title": "",
      "description_body": "",
      "mastery": "",
      "misconception": "",
      "keywords": [],
      "source_evidence": [],
      "types": []
    }}
  ]
}}

LOCKED TOPICS:
{chr(10).join(f"{i + 1}. {t}" for i, t in enumerate(locked_topics))}

VALIDATION ERRORS TO FIX:
{chr(10).join(f"{i + 1}. {e}" for i, e in enumerate(validation_errors))}

STRICT REPAIR RULES:
- Do not shrink the map.
- Preserve all valid existing normal concept rows.
- Add missing normal concepts for locked topics that have no concepts.
- Reassign concepts to the correct locked topic when topic placement is wrong.
- Use only the locked topics listed above.
- Do not create Overview, Introduction, Exercise, Practice, Examples, Activity, or Miscellaneous topics unless one is explicitly present in locked topics.
- Do not create culmination rows. Culmination rows are generated by code after this repair.
- Do not create duplicate concepts.
- Do not merge two textbook topics into one concept.
- Keep each concept within its own topic scope.
- Misconception must appear once only and must be specific.
- Types must use source-backed full question prompts only.
- Do not shorten source questions.
- Do not write source labels such as Example 3, Exercise 1.2, Fig 6.4, Table 1, or page numbers.
- Return the full repaired concept map, not only changed rows.

ACADEMIC FLEXIBILITY:
- Do not force equal concept counts across topics.
- A topic may have one concept if it is genuinely narrow.
- A topic may have multiple concepts if the source teaches multiple distinct objectives.
- Do not create filler concepts just to increase count.
- Do not force Types into purely definitional concepts.
- Add Types only when source-backed assessable tasks exist.

CURRENT CONCEPT MAP:
{json.dumps({"concepts": [_concept_to_dict(c) for c in current_rows]}, ensure_ascii=False, indent=2)}

QUESTION / TASK INVENTORY:
{json.dumps(_slim_inventory(question_inventory), ensure_ascii=False, indent=2)}

CHAPTER SOURCE:
{chapter_text}
""".strip()


def build_repair_prompt(
    cfg: RunConfig,
    concepts: list[ConceptWithTypes],
    errors: list[str],
    chapter_text: str,
    inventory: list[dict],
) -> str:
    """Backward-compatible wrapper around :func:`build_strict_repair_prompt`."""
    return build_strict_repair_prompt(
        locked_topics=canonical_topics(cfg),
        current_rows=concepts,
        validation_errors=errors,
        chapter_text=chapter_text,
        question_inventory=inventory,
    )


# --------------------------------------------------------------------------- #
# JSON parsing + orchestration
# --------------------------------------------------------------------------- #

def _parse_case(raw: dict) -> MinedCase:
    return MinedCase(
        case_id=str(raw.get("case_id") or ""),
        source_question_id=str(raw.get("source_question_id") or ""),
        case_prompt=str(raw.get("case_prompt") or ""),
        case_signature=str(raw.get("case_signature") or ""),
    )


def _parse_type(raw: dict) -> MinedType:
    cases_raw = raw.get("cases") or raw.get("case_prompts") or []
    return MinedType(
        type_id=str(raw.get("type_id") or ""),
        type_title=str(raw.get("type_title") or ""),
        type_description=str(raw.get("type_description") or ""),
        task_pattern=str(raw.get("task_pattern") or ""),
        topic_hint=str(raw.get("topic_hint") or ""),
        concept_match_hint=str(raw.get("concept_match_hint") or ""),
        source_question_ids=[str(x) for x in (raw.get("source_question_ids") or [])],
        cases=[_parse_case(c) for c in cases_raw if isinstance(c, dict)],
    )


def _parse_concept(raw: dict) -> ConceptWithTypes:
    kws = raw.get("keywords") or []
    if isinstance(kws, str):
        kws = [k.strip() for k in kws.split(",") if k.strip()]
    evidence = raw.get("source_evidence") or []
    if isinstance(evidence, str):
        evidence = [evidence] if evidence.strip() else []
    return ConceptWithTypes(
        concept_id=str(raw.get("concept_id") or ""),
        topic=str(raw.get("topic") or ""),
        parent_concept=str(raw.get("parent_concept") or ""),
        concept_title=str(raw.get("concept_title") or raw.get("concept") or ""),
        description_body=str(raw.get("description_body") or ""),
        mastery=str(raw.get("mastery") or ""),
        misconception=(str(raw.get("misconception")).strip() or None)
        if raw.get("misconception") else None,
        keywords=[str(k) for k in kws],
        source_evidence=[str(e) for e in evidence],
        types=[_parse_type(t) for t in (raw.get("types") or []) if isinstance(t, dict)],
        is_culmination=bool(raw.get("is_culmination")),
    )


def _concept_to_dict(c: ConceptWithTypes) -> dict:
    return {
        "concept_id": c.concept_id,
        "topic": c.topic,
        "parent_concept": c.parent_concept,
        "concept_title": c.concept_title,
        "description_body": c.description_body,
        "mastery": c.mastery,
        "misconception": c.misconception or "",
        "keywords": c.keywords,
        "source_evidence": c.source_evidence,
        "is_culmination": c.is_culmination,
        "types": [
            {
                "type_id": t.type_id,
                "type_title": t.type_title,
                "type_description": t.type_description,
                "task_pattern": t.task_pattern,
                "topic_hint": t.topic_hint,
                "concept_match_hint": t.concept_match_hint,
                "source_question_ids": t.source_question_ids,
                "cases": [
                    {
                        "case_id": cs.case_id,
                        "source_question_id": cs.source_question_id,
                        "case_prompt": cs.case_prompt,
                        "case_signature": cs.case_signature,
                    }
                    for cs in t.cases
                ],
            }
            for t in c.types
        ],
    }


def parse_llm_response(data: dict) -> list[ConceptWithTypes]:
    rows = data.get("concepts") or data.get("rows") or []
    out: list[ConceptWithTypes] = []
    for raw in rows:
        if not isinstance(raw, dict):
            continue
        c = _parse_concept(raw)
        if c.concept_title:
            out.append(c)
    return out


def build_output_rows(
    cfg: RunConfig, concepts: list[ConceptWithTypes],
) -> tuple[dict, list[dict]]:
    """Return (meta, workbook-oriented rows)."""
    topics = canonical_topics(cfg)
    by_topic: dict[str, list[ConceptCore]] = {}
    for c in concepts:
        if is_culmination_row(c):
            continue
        t = topic_display_name(c.topic)
        by_topic.setdefault(t, []).append(c)

    rows: list[dict] = []
    for concept in concepts:
        topic = topic_display_name(concept.topic)
        rows.append({
            "chapter_tag": chapter_tag(cfg),
            "chapter_duration_minutes": cfg.chapter_duration_minutes,
            "topic_name": topic,
            "topic_display_name": topic,
            "topic_tag": topic_tag(cfg, topic, "PL"),
            "parent_concept": concept.parent_concept,
            "concept_title": concept.concept_title,
            "concept_display_name": concept.concept_title,
            "concept_tag": concept_tag(cfg, concept, "PL"),
            "concept_description": render_concept_description(concept),
            "keywords": ", ".join(
                k.lower().strip() for k in concept.keywords if k.strip()),
            "topic_concept_labels": topic_concept_labels(by_topic.get(topic, [])),
        })
    meta = {
        "chapter_tag": chapter_tag(cfg),
        "chapter_duration_minutes": cfg.chapter_duration_minutes,
        "topics": topics,
        "topic_descriptions": {},
        "chapter_description": "",
    }
    return meta, rows


def to_legacy_records(rows: list[dict]) -> list[dict]:
    """Convert V2 output rows to the legacy deposit schema."""
    out: list[dict] = []
    for row in rows:
        title = norm(row.get("concept_title", ""))
        if not title:
            continue
        out.append({
            "topic": row.get("topic_name") or row.get("topic", "General"),
            "parent_concept": row.get("parent_concept", ""),
            "concept_title": title,
            "concept_details": row.get("concept_description", ""),
            "keywords": row.get("keywords", ""),
        })
    return out


def generate_post_learning_concepts_safe(
    *,
    locked_topics: list[str],
    chapter_text: str,
    question_inventory: list[dict],
    call_llm_json: Callable[[str, str], dict],
    build_master_prompt: Callable[[], str],
    validate_structural: Callable[[list[ConceptRow]], list[str]] | None = None,
    log: Callable[[str, str], None] | None = None,
) -> list[ConceptRow]:
    """Master prompt → coverage validation → repair → fill → culmination → pre-deposit."""
    def _log(msg: str, level: str = "info") -> None:
        if log:
            log(msg, level)

    system = (
        "You are a strict source-grounded curriculum engine. "
        "Return ONLY valid JSON matching the requested schema."
    )

    def _coverage_errors(rows: list[ConceptRow]) -> list[str]:
        return validate_locked_topic_coverage(
            locked_topics=locked_topics,
            rows=rows,
            min_normal_concepts_per_topic=1,
        )

    def _structural_errors(rows: list[ConceptRow]) -> list[str]:
        return validate_structural(rows) if validate_structural else []

    def _normalize_topics(rows: list[ConceptRow]) -> list[ConceptRow]:
        rows, snapped = snap_rows_to_locked_topics(rows, locked_topics)
        if snapped:
            _log(f"Snapped {snapped} concept(s) to locked topic names.")
        rows, reassigned = reassign_misplaced_concepts(rows, locked_topics)
        if reassigned:
            _log(f"Reassigned {reassigned} concept(s) to uncovered locked topics.")
        return rows

    _log(f"Locked topics: {len(locked_topics)}")
    data = call_llm_json(system, build_master_prompt())
    rows = strip_model_culmination_rows(parse_llm_response(data))
    rows = sanitize_concept_cases(rows, chapter_text=chapter_text)
    rows = _normalize_topics(rows)

    normal_before = len(rows)
    coverage_errors = _coverage_errors(rows)
    structural_errors = _structural_errors(rows)
    all_errors = coverage_errors + structural_errors
    _log(f"Normal concepts before repair: {normal_before}")
    _log(f"Coverage errors before repair: {len(coverage_errors)}")

    for attempt in range(2):
        if not all_errors:
            break
        repair_prompt = build_strict_repair_prompt(
            locked_topics=locked_topics,
            current_rows=rows,
            validation_errors=all_errors,
            chapter_text=chapter_text,
            question_inventory=question_inventory,
        )
        _log(
            f"Concept Map V2: {len(all_errors)} validation error(s) — "
            f"strict repair pass {attempt + 1}.",
            "warning",
        )
        repaired = call_llm_json(system, repair_prompt)
        rows = strip_model_culmination_rows(parse_llm_response(repaired))
        rows = sanitize_concept_cases(rows, chapter_text=chapter_text)
        rows = _normalize_topics(rows)
        coverage_errors = _coverage_errors(rows)
        structural_errors = _structural_errors(rows)
        all_errors = coverage_errors + structural_errors

    normal_after_repair = len(rows)
    _log(f"Normal concepts after repair: {normal_after_repair}")
    _log(f"Coverage errors after repair: {len(coverage_errors)}")

    for fill_attempt in range(2):
        missing_topics = topics_missing_coverage(locked_topics, rows)
        if not missing_topics:
            break
        fill_prompt = build_missing_topic_fill_prompt(
            missing_topics=missing_topics,
            current_rows=rows,
            chapter_text=chapter_text,
            question_inventory=question_inventory,
            locked_topics=locked_topics,
        )
        _log(
            f"Concept Map V2: GPT fill pass {fill_attempt + 1} for "
            f"{len(missing_topics)} uncovered topic(s): "
            f"{', '.join(missing_topics)}.",
            "warning",
        )
        filled = call_llm_json(system, fill_prompt)
        new_rows = strip_model_culmination_rows(parse_llm_response(filled))
        new_rows = sanitize_concept_cases(new_rows, chapter_text=chapter_text)
        rows = merge_new_concept_rows(rows, new_rows)
        rows = _normalize_topics(rows)

        for topic in topics_missing_coverage(locked_topics, rows):
            single_prompt = build_single_topic_fill_prompt(
                topic=topic,
                current_rows=rows,
                chapter_text=chapter_text,
                question_inventory=question_inventory,
                locked_topics=locked_topics,
            )
            _log(
                f"Concept Map V2: GPT single-topic fill for '{topic}'.",
                "warning",
            )
            single = call_llm_json(system, single_prompt)
            added = strip_model_culmination_rows(parse_llm_response(single))
            added = sanitize_concept_cases(added, chapter_text=chapter_text)
            rows = merge_new_concept_rows(rows, added)
            rows = _normalize_topics(rows)

        coverage_errors = _coverage_errors(rows)
        structural_errors = _structural_errors(rows)
        _log(
            f"Normal concepts after GPT fill pass {fill_attempt + 1}: {len(rows)}; "
            f"coverage errors: {len(coverage_errors)}."
        )

    coverage_errors = _coverage_errors(rows)
    if coverage_errors:
        repair_prompt = build_strict_repair_prompt(
            locked_topics=locked_topics,
            current_rows=rows,
            validation_errors=coverage_errors,
            chapter_text=chapter_text,
            question_inventory=question_inventory,
        )
        _log(
            f"Concept Map V2: final GPT coverage repair for "
            f"{len(coverage_errors)} error(s).",
            "warning",
        )
        repaired = call_llm_json(system, repair_prompt)
        rows = strip_model_culmination_rows(parse_llm_response(repaired))
        rows = sanitize_concept_cases(rows, chapter_text=chapter_text)
        rows = _normalize_topics(rows)
        coverage_errors = _coverage_errors(rows)
        structural_errors = _structural_errors(rows)

    if structural_errors:
        repair_prompt = build_strict_repair_prompt(
            locked_topics=locked_topics,
            current_rows=rows,
            validation_errors=structural_errors,
            chapter_text=chapter_text,
            question_inventory=question_inventory,
        )
        _log(
            f"Concept Map V2: {len(structural_errors)} structural error(s) — "
            "final structural repair pass.",
            "warning",
        )
        repaired = call_llm_json(system, repair_prompt)
        rows = strip_model_culmination_rows(parse_llm_response(repaired))
        rows = sanitize_concept_cases(rows, chapter_text=chapter_text)
        rows = _normalize_topics(rows)
        coverage_errors = _coverage_errors(rows)
        structural_errors = _structural_errors(rows)

    if coverage_errors:
        raise RuntimeError(
            "Concept map failed locked topic coverage before culmination.\n"
            + "\n".join(coverage_errors)
        )
    if structural_errors:
        raise RuntimeError(
            "Concept map validation failed:\n" + "\n".join(structural_errors)
        )

    normal_after = len([r for r in rows if not is_culmination_row(r)])
    rows = ensure_exactly_one_culmination_per_locked_topic(
        locked_topics=locked_topics,
        rows=rows,
    )
    culmination_count = sum(1 for r in rows if is_culmination_row(r))
    _log(f"Culmination rows generated: {culmination_count}")
    _log(
        f"Final rows before deposit: {normal_after} normal + "
        f"{culmination_count} culmination"
    )

    pre_deposit_errors = validate_pre_deposit(
        locked_topics=locked_topics,
        rows=rows,
    )
    if pre_deposit_errors:
        raise RuntimeError(
            "Concept map failed pre-deposit validation.\n"
            + "\n".join(pre_deposit_errors)
        )

    return rows


def generate_concept_map_v2(
    cfg: RunConfig,
    chapter_text: str,
    inventory: list[dict],
    *,
    call_llm_json: Callable[[str, str], dict],
    log: Callable[[str, str], None] | None = None,
) -> tuple[dict, list[dict], list[ConceptWithTypes]]:
    """Run the V2 pipeline: master prompt → coverage → repair → culmination → render."""
    assert_finalized_config(cfg)
    locked_topics = canonical_topics(cfg)

    concepts = generate_post_learning_concepts_safe(
        locked_topics=locked_topics,
        chapter_text=chapter_text,
        question_inventory=inventory,
        call_llm_json=call_llm_json,
        build_master_prompt=lambda: build_concept_map_prompt(
            cfg, chapter_text, inventory),
        validate_structural=lambda rows: validate_concept_map(cfg, rows),
        log=log,
    )

    meta, rows = build_output_rows(cfg, concepts)
    if log:
        log(
            f"Concept Map V2: {len(concepts)} concept(s) ready for deposit.",
            "success",
        )
    return meta, rows, concepts
