"""Concept Map V2 — source-locked pipeline, prompt, validation, and renderer.

Replaces the multi-pass staged concept mapper with one master LLM call (+ optional
repair) and deterministic post-processing:

1. Topics locked to textbook/source headings (``expected_topics``).
2. Chapter tags and subject prefixes generated by code, not the model.
3. ``topic_display_name`` is exactly the topic name.
4. ``topic_concept_labels`` uses concept title, not display name.
5. Misconception appears once only.
6. Types/Cases structured first, then rendered into ``concept_description`` once.
7. Cases are sub-types under Types and must carry full source questions.
8. Examples/questions copied from source inventory — never shortened.
9. Chapter duration from finalized config, not the model.
10. English Literature uses the literature template and rejects pedagogy concepts.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable

from .concept_cleanup import neutralize_source_artifacts_preserve_images
from .mmd_figures import figure_markdown_index_from_mmd, inline_figures_in_text

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

SUBJECT_CODE: dict[str, str] = {
    "mathematics": "MA",
    "physics": "PH",
    "chemistry": "CH",
    "biology": "BI",
    "science": "SC",
    "geography": "SS",
    "history": "SS",
    "civics": "SS",
    "economics": "SS",
    "political science": "SS",
    "social science": "SS",
    "english": "EL",
    "english literature": "EL",
}

SUBJECT_DISPLAY: dict[str, str] = {
    "mathematics": "Mathematics",
    "physics": "Physics",
    "chemistry": "Chemistry",
    "biology": "Biology",
    "science": "Science",
    "geography": "Social_Science",
    "history": "Social_Science",
    "civics": "Social_Science",
    "economics": "Social_Science",
    "political science": "Social_Science",
    "social science": "Social_Science",
    "english": "English_Literature",
    "english literature": "English_Literature",
}

ENGLISH_LIT_BANNED_CONCEPT_TERMS = [
    "pre-reading",
    "prediction",
    "discussion",
    "reading in manageable parts",
    "oral checks",
    "informal letter writing",
    "family news",
    "lesson plan",
    "teacher activity",
    "classroom activity",
    "pedagogy",
    "worksheet creation",
]

DEFAULT_ENGLISH_LIT_TEMPLATE = [
    "Text Context and Genre",
    "Plot Sequence and Conflict",
    "Character Motivation and Response",
    "Themes, Values and Message",
    "Language, Tone and Literary Devices",
    "Key Extract Interpretation",
    "Vocabulary and Expressions in Context",
    "Answer Framing for Text-Based Questions",
]

_SOURCE_ARTIFACT_RE = re.compile(
    r"\b(example|ex\.?|exercise|activity|activities|fig\.?|figure|table|page|mmd|mmds)\s*\d+",
    re.IGNORECASE,
)

# Figure references in case prompts → inline markdown from chapter MMD when available.
_FIG_REF_INLINE_RE = re.compile(
    r"\b(Fig(?:ure)?\.?\s*(\d+(?:\.\d+)*))",
    re.IGNORECASE,
)
_MARKDOWN_IMG_ANY_RE = re.compile(
    r"!\[([^\]]*)\]\(([^)]+)\)",
    re.IGNORECASE,
)

_GENERIC_MISCONCEPTIONS = [
    "students may get confused",
    "learners may misunderstand the concept",
    "students may not understand",
    "students may confuse this with other concepts",
]


# --------------------------------------------------------------------------- #
# Data classes
# --------------------------------------------------------------------------- #

@dataclass
class RunConfig:
    board: str
    class_num: int
    subject: str
    chapter: str
    publication: str
    chapter_duration_minutes: int
    expected_topics: list[str]
    allow_introduction_topic: bool = False
    english_literature_template_concepts: list[str] | None = None


@dataclass
class MinedCase:
    case_id: str
    source_question_id: str
    case_prompt: str
    case_signature: str = ""


@dataclass
class MinedType:
    type_id: str
    type_title: str
    type_description: str = ""
    task_pattern: str = ""
    topic_hint: str = ""
    concept_match_hint: str = ""
    source_question_ids: list[str] = field(default_factory=list)
    cases: list[MinedCase] = field(default_factory=list)


@dataclass
class ConceptCore:
    concept_id: str
    topic: str
    parent_concept: str
    concept_title: str
    description_body: str
    mastery: str
    keywords: list[str]
    source_evidence: list[str] = field(default_factory=list)
    misconception: str | None = None


@dataclass
class ConceptWithTypes(ConceptCore):
    types: list[MinedType] = field(default_factory=list)


# --------------------------------------------------------------------------- #
# String / tag helpers (code-owned — never LLM)
# --------------------------------------------------------------------------- #

def norm(s: str) -> str:
    return re.sub(r"\s+", " ", str(s or "")).strip()


def slug(s: str) -> str:
    return re.sub(r"^_+|_+$", "",
                  re.sub(r"[^A-Za-z0-9]+", "_",
                         norm(s).replace("'", "").replace("'", "")))


def strip_numbering(s: str) -> str:
    out = norm(s)
    out = re.sub(
        r"^(chapter|unit|topic|section|exercise|ex)\s*\d+([.\-:]\d+)*\s*[:.)-]?\s*",
        "", out, flags=re.IGNORECASE)
    out = re.sub(r"^\d+([.\-:]\d+)*\s*[:.)-]?\s*", "", out)
    return out.strip()


def subject_code(subject: str) -> str:
    key = subject.lower().strip()
    return SUBJECT_CODE.get(key) or slug(subject)[:2].upper()


def subject_display(subject: str) -> str:
    key = subject.lower().strip()
    return SUBJECT_DISPLAY.get(key) or slug(subject)


def board_code(board: str) -> str:
    return board.upper().strip()


def class_code(class_num: int) -> str:
    return str(class_num).zfill(2)


def concept_prefix(cfg: RunConfig) -> str:
    return f"{class_code(cfg.class_num)}{board_code(cfg.board)[:2]}{subject_code(cfg.subject)}"


def chapter_tag(cfg: RunConfig) -> str:
    return (
        f"{class_code(cfg.class_num)}_{subject_display(cfg.subject)}_"
        f"{board_code(cfg.board)}_{slug(cfg.publication)}"
    )


def topic_display_name(topic: str) -> str:
    return strip_numbering(topic)


def topic_tag(cfg: RunConfig, topic: str, stage: str = "PL") -> str:
    return f"{concept_prefix(cfg)}_{slug(cfg.chapter)}_{stage}_{slug(topic_display_name(topic))}"


def concept_tag(cfg: RunConfig, concept: ConceptCore, stage: str = "PL") -> str:
    return f"{concept_prefix(cfg)}_{slug(cfg.chapter)}_{stage}_{slug(concept.concept_title)}"


def topic_concept_labels(concepts: list[ConceptCore]) -> str:
    return ", ".join(c.concept_title for c in concepts)


def is_english_literature(cfg: RunConfig) -> bool:
    return cfg.subject.lower().strip() in {"english", "english literature"}


def assert_finalized_config(cfg: RunConfig) -> None:
    if not cfg.publication:
        raise ValueError(
            "Missing publication. Chapter tag must include publication.")
    if not cfg.chapter_duration_minutes or cfg.chapter_duration_minutes <= 0:
        raise ValueError(
            "Missing finalized chapter duration. Do not let the LLM estimate this.")
    if not cfg.expected_topics:
        raise ValueError(
            "Missing expected_topics. Lock topics from textbook TOC/source "
            "headings before concept extraction.")


def canonical_topics(cfg: RunConfig) -> list[str]:
    topics = [topic_display_name(t) for t in cfg.expected_topics if topic_display_name(t)]
    if not cfg.allow_introduction_topic:
        topics = [t for t in topics if not re.match(r"^(introduction|overview)$", t, re.I)]
    if is_english_literature(cfg):
        topics = [cfg.chapter]
    seen: set[str] = set()
    out: list[str] = []
    for t in topics:
        key = t.lower()
        if key not in seen:
            seen.add(key)
            out.append(t)
    return out


def parse_duration_minutes(text: str) -> int | None:
    m = re.search(r"(\d+)", text or "")
    return int(m.group(1)) if m else None


def run_config_from_meta(
    *,
    board: str = "",
    grade: str = "",
    subject: str = "",
    chapter_title: str = "",
    publication: str = "",
    chapter_duration: str = "",
    expected_topics: list[str],
    allow_introduction_topic: bool | None = None,
) -> RunConfig:
    """Build a :class:`RunConfig` from chapter/upload metadata."""
    class_num = 10
    m = re.search(r"\d+", grade or "")
    if m:
        class_num = int(m.group())
    duration = parse_duration_minutes(chapter_duration)
    if not duration:
        # Deterministic fallback: ~60 minutes per locked topic, bounded.
        n = max(len(expected_topics), 1)
        duration = max(180, min(720, n * 60))
    if allow_introduction_topic is None:
        allow_introduction_topic = any(
            re.match(r"^introduction$", topic_display_name(t), re.I)
            for t in expected_topics
        )
    pub = norm(publication) or "NCERT"
    return RunConfig(
        board=board or "CBSE",
        class_num=class_num,
        subject=subject or "General",
        chapter=chapter_title or "Chapter",
        publication=pub,
        chapter_duration_minutes=duration,
        expected_topics=expected_topics,
        allow_introduction_topic=allow_introduction_topic,
    )


def has_source_artifact(text: str) -> bool:
    return bool(_SOURCE_ARTIFACT_RE.search(text or ""))


def sanitize_case_prompt(prompt: str, *, chapter_text: str = "") -> str:
    """Rewrite source-artifact labels; inline figure images from chapter MMD."""
    p = norm(prompt)
    if not p:
        return p
    fig_index = figure_markdown_index_from_mmd(chapter_text)
    p = inline_figures_in_text(p, fig_index)
    p = neutralize_source_artifacts_preserve_images(p)
    return clean_one_line(p)


def sanitize_concept_cases(
    concepts: list[ConceptWithTypes],
    *,
    chapter_text: str = "",
) -> list[ConceptWithTypes]:
    """Deterministically clean all case prompts before validation."""
    for concept in concepts:
        for type_ in concept.types:
            for case in type_.cases:
                case.case_prompt = sanitize_case_prompt(
                    case.case_prompt, chapter_text=chapter_text,
                )
    return concepts


def clean_one_line(s: str) -> str:
    out = norm(s).replace("MMDs", "chapter").replace("MMD", "chapter")
    # Protect URLs before normalizing section separators (avoid breaking https://).
    urls: list[str] = []

    def _stash_url(match: re.Match[str]) -> str:
        urls.append(match.group(0))
        return f"__URL_{len(urls) - 1}__"

    out = re.sub(r"https?://\S+", _stash_url, out)
    out = re.sub(r"\s*//\s*", " // ", out)
    for i, url in enumerate(urls):
        out = out.replace(f"__URL_{i}__", url)
    return out.strip()


def sanitize_description_body(s: str) -> str:
    out = str(s or "")
    out = re.sub(r"^Description:\s*", "", out, flags=re.I)
    out = re.sub(r"\s*//\s*Types:\s*.*$", "", out, flags=re.I | re.S)
    out = re.sub(r"\s*//\s*Misconceptions?:\s*.*$", "", out, flags=re.I | re.S)
    out = re.sub(r"\n?Achieving Mastery:\s*.*$", "", out, flags=re.I | re.S)
    out = clean_one_line(out.strip())
    if not out:
        raise ValueError("Empty description_body after sanitization.")
    return out


def sanitize_mastery(s: str) -> str:
    out = re.sub(r"^Achieving Mastery:\s*", "", str(s or ""), flags=re.I).strip()
    out = clean_one_line(out)
    if not out:
        raise ValueError("Missing Achieving Mastery line.")
    return re.sub(r"[.]*$", ".", out)


def sanitize_misconception(s: str | None) -> str | None:
    if not s:
        return None
    out = re.sub(r"^Misconceptions?:\s*", "", str(s), flags=re.I)
    out = re.sub(r"\b(n/a|none|not applicable)\b", "", out, flags=re.I).strip()
    out = clean_one_line(out)
    if not out:
        return None
    if any(bad in out.lower() for bad in _GENERIC_MISCONCEPTIONS):
        return None
    return re.sub(r"[.]*$", ".", out)


def case_prompt_is_valid(prompt: str) -> bool:
    p = norm(prompt)
    if not p or len(p) < 20:
        return False
    # Alt text in inlined figure images may retain Fig. N labels — ignore those.
    stripped = re.sub(r"!\[[^\]]*\]\([^)]+\)", "[figure]", p)
    return not has_source_artifact(stripped)


def render_types(types: list[MinedType]) -> str:
    rendered: list[str] = []
    for type_ in types:
        valid_cases = [c for c in type_.cases if case_prompt_is_valid(c.case_prompt)]
        if not valid_cases:
            continue
        case_text = " ".join(
            f"Case {str(i + 1).zfill(2)}: {clean_one_line(c.case_prompt)}"
            for i, c in enumerate(valid_cases)
        )
        rendered.append(
            f"Type {str(len(rendered) + 1).zfill(2)}: "
            f"{clean_one_line(type_.type_title)} {case_text}"
        )
    return " ".join(rendered)


def render_concept_description(concept: ConceptWithTypes) -> str:
    body = sanitize_description_body(concept.description_body)
    mastery = sanitize_mastery(concept.mastery)
    misconception = sanitize_misconception(concept.misconception)
    types_text = render_types(concept.types or [])
    sections = [
        f"Description: {body}\nAchieving Mastery: {mastery}",
        f"Misconception: {misconception}" if misconception else None,
        f"Types: {types_text}" if types_text else None,
    ]
    return " // ".join(s for s in sections if s)


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #

def validate_concept_map(cfg: RunConfig, concepts: list[ConceptWithTypes]) -> list[str]:
    errors: list[str] = []
    topics = canonical_topics(cfg)
    allowed = {t.lower() for t in topics}
    seen_concepts: dict[str, str] = {}
    seen_type_assignments: dict[str, str] = {}
    seen_source_questions: dict[str, str] = {}

    for c in concepts:
        topic = topic_display_name(c.topic)
        if topic.lower() not in allowed:
            errors.append(
                f'Invalid topic "{c.topic}". Must be one of: {" | ".join(topics)}')
        if (re.match(r"^(overview|introduction)$", topic, re.I)
                and not cfg.allow_introduction_topic
                and not is_english_literature(cfg)):
            errors.append(
                f'Unwanted topic "{topic}". Do not create Overview/Introduction '
                "unless source requires it.")

        if is_english_literature(cfg):
            title_l = c.concept_title.lower()
            bad = next((t for t in ENGLISH_LIT_BANNED_CONCEPT_TERMS if t in title_l), None)
            if bad:
                errors.append(
                    f'English Literature concept "{c.concept_title}" is invalid '
                    f"pedagogy/activity content: {bad}")

        key = slug(c.concept_title).lower()
        if key in seen_concepts:
            errors.append(
                f'Duplicate concept "{c.concept_title}" appears in both '
                f'"{seen_concepts[key]}" and "{topic}".')
        else:
            seen_concepts[key] = topic

        if len(re.findall(r"Misconceptions?:", c.misconception or "", re.I)) > 1:
            errors.append(f'Duplicate Misconception section in "{c.concept_title}".')
        if c.misconception and not sanitize_misconception(c.misconception):
            errors.append(f'Generic or invalid misconception in "{c.concept_title}".')

        for t in c.types or []:
            if not t.cases:
                errors.append(
                    f'Type "{t.type_title}" under "{c.concept_title}" has no '
                    "source-backed Cases.")
            if t.type_id in seen_type_assignments:
                errors.append(
                    f"Type {t.type_id} assigned to more than one concept: "
                    f'"{seen_type_assignments[t.type_id]}" and "{c.concept_title}".')
            else:
                seen_type_assignments[t.type_id] = c.concept_title
            for qid in t.source_question_ids or []:
                if qid in seen_source_questions:
                    errors.append(
                        f"Question {qid} assigned to multiple concepts: "
                        f'"{seen_source_questions[qid]}" and "{c.concept_title}".')
                else:
                    seen_source_questions[qid] = c.concept_title
            for cs in t.cases or []:
                if not case_prompt_is_valid(cs.case_prompt):
                    errors.append(
                        f'Invalid/short/source-artifact Case in "{c.concept_title}" > '
                        f'"{t.type_title}": "{cs.case_prompt}"')
    return errors


# --------------------------------------------------------------------------- #
# Prompts
# --------------------------------------------------------------------------- #

def _slim_inventory(items: list[dict]) -> list[dict]:
    """Pass only fields the V2 master prompt needs."""
    out: list[dict] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        out.append({
            "qid": item.get("qid", ""),
            "source_kind": item.get("source_kind", "other"),
            "source_label": item.get("source_label", ""),
            "topic_hint": item.get("topic_hint", ""),
            "raw_task": item.get("raw_task", ""),
            "normalized_task": item.get("normalized_task", ""),
            "raw_solution_or_answer": item.get("raw_solution_or_answer", ""),
            "shared_context": item.get("shared_context", ""),
            "subpart_label": item.get("subpart_label", ""),
            "order_index": item.get("order_index", 0),
        })
    return out


def build_concept_map_prompt(
    cfg: RunConfig, chapter_text: str, inventory: list[dict],
) -> str:
    assert_finalized_config(cfg)
    topics = canonical_topics(cfg)
    template = (
        cfg.english_literature_template_concepts or DEFAULT_ENGLISH_LIT_TEMPLATE
    )
    import json
    inv_json = json.dumps(_slim_inventory(inventory), ensure_ascii=False, indent=2)
    topic_lines = "\n".join(f"  {i + 1}. {t}" for i, t in enumerate(topics))
    template_lines = "\n".join(f"  {i + 1}. {x}" for i, x in enumerate(template))

    return f"""
You are a strict source-grounded concept mapping engine for school curriculum.

Return ONLY strict JSON:
{{
  "concepts": [
    {{
      "concept_id": "CONCEPT-0001",
      "topic": "",
      "parent_concept": "",
      "concept_title": "",
      "description_body": "",
      "mastery": "",
      "misconception": "",
      "keywords": [],
      "source_evidence": [],
      "types": [
        {{
          "type_id": "TYPE-0001",
          "type_title": "",
          "type_description": "",
          "task_pattern": "",
          "topic_hint": "",
          "concept_match_hint": "",
          "source_question_ids": ["QINV-0001"],
          "cases": [
            {{
              "case_id": "CASE-0001",
              "source_question_id": "QINV-0001",
              "case_prompt": "",
              "case_signature": ""
            }}
          ]
        }}
      ]
    }}
  ],
  "audit": {{
    "chapter_tag": "{chapter_tag(cfg)}",
    "chapter_duration_minutes": {cfg.chapter_duration_minutes},
    "topic_count": {len(topics)},
    "coverage_notes": []
  }}
}}

NON-NEGOTIABLE RUN CONTEXT:
- Board: {cfg.board}
- Class: {cfg.class_num}
- Subject: {cfg.subject}
- Chapter: {cfg.chapter}
- Publication: {cfg.publication}
- Chapter tag must be exactly: {chapter_tag(cfg)}
- Chapter duration must be exactly: {cfg.chapter_duration_minutes}
- Allowed topics, in exact reading order:
{topic_lines}

TOPIC RULES:
- Use ONLY the allowed topics above.
- topic must exactly match one allowed topic.
- Do not create Overview, Introduction, Miscellaneous, Practice, Exercise, Examples, or Activity topics unless they are explicitly present in the allowed topic list.
- Do not duplicate a concept across two topics.
- BPT, CBPT, theorem variants, formulas, events, characters, processes, or definitions belong only to the topic where the source teaches them most directly.
- If a later topic reuses an earlier concept, do not create it again. Mention reuse only inside the relevant Type/Case when needed.

CONCEPT RULES:
- A concept is a durable teachable mastery objective.
- Do not create rows for cases, examples, individual questions, generic activities, or teacher methods.
- concept_title must be the title name only. No display prefix, no topic number, no chapter number.
- Use textbook/source vocabulary.
- Avoid repeated sibling openers.
- parent_concept must be a compact cluster name, not a duplicate of topic.
- keywords: 3 to 6 lowercase keywords.

DESCRIPTION RULES:
- description_body must contain only the teachable explanation.
- Do not include "Description:", "Types:", "Case:", "Misconception:", or "Achieving Mastery:" inside description_body.
- 45 to 90 words unless the concept is very simple.
- Keep the scope of the concept tight. Do not pull types/cases/details from the next concept.
- mastery must be one short sentence saying what the learner can do after mastering this concept.
- misconception must appear at most once and must be specific.
- Do not write generic misconceptions.
- Do not write N/A, None, Not applicable, filler, or placeholders.

TYPES AND CASES:
- Types classify assessable question/task varieties under that exact concept.
- Cases are sub-types/examples under Types.
- If no source-backed Case exists for a Type, do not list that Type.
- If a concept has no meaningful assessable source task, use an empty types array.
- Every Case must be copied from the source question/task inventory as a full teacher-executable prompt.
- Do not shorten questions.
- Preserve all numbers, expressions, diagrams/tables/passages context, names, dates, givens, conditions, quotations, and exact asks.
- Do not write "Example 3", "Exercise 1.2", "Fig 6.4", "Table 1", page references, or source labels in case_prompt.
- Substitute the actual content instead.
- Include as many source examples as available for each Type.
- Every inventory item must be assigned to exactly one concept unless it is truly rhetorical/non-assessable.
- Do not assign one question/task to multiple concepts.
- Culmination or mixed Types are allowed only when a source task combines multiple concepts from the same topic.

SUBJECT-SPECIFIC RULES:
- Mathematics: Types may be numerical, proof, construction, graph, theorem application, formula, diagram, reasoning, or word-problem patterns.
- Science: Types may be diagram, experiment, observation, inference, process, comparison, numerical, reasoning, or application patterns.
- Social Science: Types may be definition, cause-effect, comparison, chronology, map, source, case, data, evidence, or long-answer patterns.
- English Literature: topic must be exactly the prose/poem/drama name "{cfg.chapter}".
- English Literature must follow this concept family unless a source-specific idea clearly requires a tighter concept:
{template_lines}
- English Literature must NOT create pedagogy/activity concepts such as pre-reading prediction, oral checks, reading in parts, informal letter writing, family news, classroom discussion, or lesson planning unless the chapter itself assesses it as text content.

OUTPUT SAFETY:
- Return JSON only.
- No markdown.
- No commentary.
- No source-artifact labels.
- Never use the words MMD or MMDs.

QUESTION / TASK INVENTORY:
{inv_json}

CHAPTER SOURCE:
{chapter_text}
""".strip()


def build_repair_prompt(
    cfg: RunConfig,
    concepts: list[ConceptWithTypes],
    errors: list[str],
    chapter_text: str,
    inventory: list[dict],
) -> str:
    import json
    topics = canonical_topics(cfg)
    topic_lines = "\n".join(f"  {i + 1}. {t}" for i, t in enumerate(topics))
    err_lines = "\n".join(f"{i + 1}. {e}" for i, e in enumerate(errors))
    payload = {"concepts": [_concept_to_dict(c) for c in concepts]}
    inv_json = json.dumps(_slim_inventory(inventory), ensure_ascii=False, indent=2)
    return f"""
Repair the concept map JSON using ONLY the listed validation errors.

Return ONLY strict JSON:
{{ "concepts": [ ...same schema... ] }}

Rules:
- Fix only the errors listed.
- Preserve valid rows, valid topics, valid descriptions, valid mastery lines, and valid types.
- Do not rewrite the full chapter.
- Do not create new topics.
- Use only these allowed topics:
{topic_lines}
- Chapter duration remains exactly {cfg.chapter_duration_minutes}.
- Chapter tag remains exactly {chapter_tag(cfg)}.
- If a Case is too short or refers to Example/Exercise/Figure/Table/page, replace it with the full actual source question from the inventory/source.
- If a Type has no valid source-backed Case, remove that Type.
- If a misconception is duplicated or generic, keep only one specific misconception or remove it.
- If a concept appears in two topics, keep it only in the source topic where it is directly taught.
- If English Literature has pedagogy/activity concepts, replace them with source-text concepts following the literature template.

VALIDATION ERRORS:
{err_lines}

CURRENT CONCEPT MAP:
{json.dumps(payload, ensure_ascii=False, indent=2)}

QUESTION / TASK INVENTORY:
{inv_json}

CHAPTER SOURCE:
{chapter_text}
""".strip()


# --------------------------------------------------------------------------- #
# JSON parsing + orchestration
# --------------------------------------------------------------------------- #

def _parse_case(raw: dict) -> MinedCase:
    return MinedCase(
        case_id=str(raw.get("case_id") or ""),
        source_question_id=str(raw.get("source_question_id") or ""),
        case_prompt=str(raw.get("case_prompt") or ""),
        case_signature=str(raw.get("case_signature") or ""),
    )


def _parse_type(raw: dict) -> MinedType:
    cases_raw = raw.get("cases") or raw.get("case_prompts") or []
    return MinedType(
        type_id=str(raw.get("type_id") or ""),
        type_title=str(raw.get("type_title") or ""),
        type_description=str(raw.get("type_description") or ""),
        task_pattern=str(raw.get("task_pattern") or ""),
        topic_hint=str(raw.get("topic_hint") or ""),
        concept_match_hint=str(raw.get("concept_match_hint") or ""),
        source_question_ids=[str(x) for x in (raw.get("source_question_ids") or [])],
        cases=[_parse_case(c) for c in cases_raw if isinstance(c, dict)],
    )


def _parse_concept(raw: dict) -> ConceptWithTypes:
    kws = raw.get("keywords") or []
    if isinstance(kws, str):
        kws = [k.strip() for k in kws.split(",") if k.strip()]
    evidence = raw.get("source_evidence") or []
    if isinstance(evidence, str):
        evidence = [evidence] if evidence.strip() else []
    return ConceptWithTypes(
        concept_id=str(raw.get("concept_id") or ""),
        topic=str(raw.get("topic") or ""),
        parent_concept=str(raw.get("parent_concept") or ""),
        concept_title=str(raw.get("concept_title") or raw.get("concept") or ""),
        description_body=str(raw.get("description_body") or ""),
        mastery=str(raw.get("mastery") or ""),
        misconception=(str(raw.get("misconception")).strip() or None)
        if raw.get("misconception") else None,
        keywords=[str(k) for k in kws],
        source_evidence=[str(e) for e in evidence],
        types=[_parse_type(t) for t in (raw.get("types") or []) if isinstance(t, dict)],
    )


def _concept_to_dict(c: ConceptWithTypes) -> dict:
    return {
        "concept_id": c.concept_id,
        "topic": c.topic,
        "parent_concept": c.parent_concept,
        "concept_title": c.concept_title,
        "description_body": c.description_body,
        "mastery": c.mastery,
        "misconception": c.misconception or "",
        "keywords": c.keywords,
        "source_evidence": c.source_evidence,
        "types": [
            {
                "type_id": t.type_id,
                "type_title": t.type_title,
                "type_description": t.type_description,
                "task_pattern": t.task_pattern,
                "topic_hint": t.topic_hint,
                "concept_match_hint": t.concept_match_hint,
                "source_question_ids": t.source_question_ids,
                "cases": [
                    {
                        "case_id": cs.case_id,
                        "source_question_id": cs.source_question_id,
                        "case_prompt": cs.case_prompt,
                        "case_signature": cs.case_signature,
                    }
                    for cs in t.cases
                ],
            }
            for t in c.types
        ],
    }


def parse_llm_response(data: dict) -> list[ConceptWithTypes]:
    rows = data.get("concepts") or data.get("rows") or []
    out: list[ConceptWithTypes] = []
    for raw in rows:
        if not isinstance(raw, dict):
            continue
        c = _parse_concept(raw)
        if c.concept_title:
            out.append(c)
    return out


def build_output_rows(
    cfg: RunConfig, concepts: list[ConceptWithTypes],
) -> tuple[dict, list[dict]]:
    """Return (meta, workbook-oriented rows)."""
    topics = canonical_topics(cfg)
    by_topic: dict[str, list[ConceptCore]] = {}
    for c in concepts:
        t = topic_display_name(c.topic)
        by_topic.setdefault(t, []).append(c)

    rows: list[dict] = []
    for concept in concepts:
        topic = topic_display_name(concept.topic)
        rows.append({
            "chapter_tag": chapter_tag(cfg),
            "chapter_duration_minutes": cfg.chapter_duration_minutes,
            "topic_name": topic,
            "topic_display_name": topic,
            "topic_tag": topic_tag(cfg, topic, "PL"),
            "parent_concept": concept.parent_concept,
            "concept_title": concept.concept_title,
            "concept_display_name": concept.concept_title,
            "concept_tag": concept_tag(cfg, concept, "PL"),
            "concept_description": render_concept_description(concept),
            "keywords": ", ".join(
                k.lower().strip() for k in concept.keywords if k.strip()),
            "topic_concept_labels": topic_concept_labels(by_topic.get(topic, [])),
        })
    meta = {
        "chapter_tag": chapter_tag(cfg),
        "chapter_duration_minutes": cfg.chapter_duration_minutes,
        "topics": topics,
        "topic_descriptions": {},
        "chapter_description": "",
    }
    return meta, rows


def to_legacy_records(rows: list[dict]) -> list[dict]:
    """Convert V2 output rows to the legacy deposit schema."""
    out: list[dict] = []
    for row in rows:
        title = norm(row.get("concept_title", ""))
        if not title:
            continue
        out.append({
            "topic": row.get("topic_name") or row.get("topic", "General"),
            "parent_concept": row.get("parent_concept", ""),
            "concept_title": title,
            "concept_details": row.get("concept_description", ""),
            "keywords": row.get("keywords", ""),
        })
    return out


def generate_concept_map_v2(
    cfg: RunConfig,
    chapter_text: str,
    inventory: list[dict],
    *,
    call_llm_json: Callable[[str, str], dict],
    log: Callable[[str, str], None] | None = None,
) -> tuple[dict, list[dict], list[ConceptWithTypes]]:
    """Run the V2 pipeline: master prompt → validate → optional repair → render."""
    def _log(msg: str, level: str = "info") -> None:
        if log:
            log(msg, level)

    assert_finalized_config(cfg)
    system = (
        "You are a strict source-grounded curriculum engine. "
        "Return ONLY valid JSON matching the requested schema."
    )
    prompt = build_concept_map_prompt(cfg, chapter_text, inventory)
    _log("Concept Map V2: running master prompt.")
    data = call_llm_json(system, prompt)
    concepts = parse_llm_response(data)
    if not concepts:
        raise RuntimeError("Concept Map V2: master prompt returned no concepts")

    concepts = sanitize_concept_cases(concepts, chapter_text=chapter_text)
    errors = validate_concept_map(cfg, concepts)
    if errors:
        _log(f"Concept Map V2: {len(errors)} validation error(s) — repair pass.", "warning")
        repair = build_repair_prompt(cfg, concepts, errors, chapter_text, inventory)
        data = call_llm_json(system, repair)
        concepts = parse_llm_response(data)
        concepts = sanitize_concept_cases(concepts, chapter_text=chapter_text)
        errors = validate_concept_map(cfg, concepts)

    if errors:
        raise RuntimeError(
            "Concept map validation failed:\n" + "\n".join(errors))

    meta, rows = build_output_rows(cfg, concepts)
    _log(f"Concept Map V2: {len(concepts)} concept(s) validated.", "success")
    return meta, rows, concepts
