"""Upload an edited Concept workbook back into a staged release.

The reviewer downloads the canonical release-bulk-import workbook, edits
it locally in Excel, and uploads the same file here. The upload is applied
as ONE recorded review round through the existing release revision trail,
then remains staged for the explicit Master resume. Publication is still a
separate hold. There is deliberately no second import semantics: the
previous path (``/data/import``) silently NO-OPed content edits on existing
concepts and forked a duplicate row on a title edit, which is exactly the
divergence this module closes.

Matching is mechanical and loud:

* primarily by the identity tag the downloaded workbook itself embeds in
  the title cells (rebuilt from the same staged payload through the same
  ``transient_release_hierarchy`` that rendered the download — one
  authority for the tag);
* fallback, for a row whose tag was lost in editing, exact
  (topic, concept title) match against the staged records;
* unmatched Post concepts are refused with their sheet and row named.
  Explicit new Pre rows may be added, including to an empty original,
  after their chapter/lane identity is checked and their provenance recorded.
  Reviewer-added Post questions are accepted only through the explicit
  reviewed Types/Cases or Concept Details question surface and receive a
  stable question identity with provenance.

Concept fields travel through the existing editable field rules. Post
question membership, wording, dependencies and reviewed Type/Case/Concept
placement travel through the explicit question review projection; Pre
questions remain generated by the prerequisite lane. Other rendered audit
columns are ignored here.
"""
from __future__ import annotations

from pathlib import Path
import copy
import hashlib
import json
from datetime import datetime, timezone
from typing import Any, Mapping

import openpyxl
from sqlalchemy.orm import Session

from .. import models
from ..bulk_import import layouts
from ..bulk_import import strip_title_tag, strip_topic_title
from ..bulk_import.layouts import WorkbookLayoutError
from . import build_concepts_release as bcr
from . import build_concepts_release_files as release_files
from . import identity
from . import generation_recovery
from . import release_review


class WorkbookEditError(ValueError):
    """The uploaded workbook cannot be applied mechanically."""


def _is_release_concept_tag(tag: object) -> bool:
    """Whether a title tag is one of Aegis' own concept identities.

    Aegis' own tags have the lane/topic/concept grammar parsed by
    ``identity.minted_concept_ordinal``.  This is a mechanical grammar check;
    whether an identity belongs to this release is checked separately against
    the target chapter/lane and staged tag map.
    """

    value = str(tag or "").strip()
    return bool(value and identity.minted_concept_ordinal(value) is not None)


def _is_expected_pre_tag(
    db: Session,
    payload: Mapping[str, Any],
    tag: object,
) -> bool:
    """Recognize a chapter's own Pre tag used as display metadata.

    Corrected canonical workbooks may have been produced by the catalogue
    importer before this staged release existed.  Their concept titles carry
    the chapter's normal ``..._PrL_T##_C##`` tag even when no staged PRC id
    exists.  Such a tag can be accepted as an addition hint only when its
    chapter/lane prefix agrees with this job; a tag from another chapter or a
    stale arbitrary identity remains a refusal.
    """

    value = str(tag or "").strip()
    if not value or not _is_release_concept_tag(value):
        return False
    try:
        chapter_id = int(payload.get("target_chapter_id") or 0)
        chapter = db.get(models.Chapter, chapter_id)
        if chapter is None:
            return False
        chapter_key = identity.chapter_key(
            chapter, chapter_id=chapter_id, session=db,
        )
    except Exception:
        return False
    return value.startswith(
        f"{chapter_key}_{identity.LANE_PRE_TOKEN}_"
    )


def _fresh_pre_concept_ids(
    records: list[Any], count: int,
) -> list[str]:
    """Mint collision-free internal Pre ids without re-keying old rows."""

    used = {
        str(row.get("_pre_concept_id") or "").strip()
        for row in records
        if isinstance(row, Mapping)
    }
    output: list[str] = []
    number = 1
    while len(output) < count:
        candidate = f"PRC-{number:04d}"
        number += 1
        if candidate in used:
            continue
        used.add(candidate)
        output.append(candidate)
    return output


def _new_pre_record(
    row: Mapping[str, Any],
    pre_concept_id: str,
    *,
    round_stamp: str,
    owner_sub: str,
) -> dict[str, Any]:
    """Build a reviewer-added Pre row from authored cells only.

    The row deliberately carries no source block, semantic topic id, or
    prerequisite provenance: those values were not supplied by the reviewer.
    Empty lane-private collections are explicit so later Pre regeneration can
    key exactly on ``_pre_concept_id`` without treating the row as a source
    capture.
    """

    return {
        "topic": str(row.get("topic") or "").strip(),
        "parent_concept": str(row.get("parent_concept") or "").strip(),
        "concept_title": str(row.get("concept_title") or "").strip(),
        "concept_details": str(row.get("concept_details") or ""),
        "keywords": str(row.get("keywords") or "").strip(),
        "_pre_concept_id": pre_concept_id,
        "_reviewed_pre_identity_tag": str(row.get("tag") or "").strip(),
        "_aegis_pre_prerequisites": [],
        "_aegis_needed_for": [],
        "_aegis_pre_related_concepts": "",
        "_aegis_pre_related_concepts_unresolved": [],
        bcr.RELEASE_ROW_LANE_FIELD: bcr.LANE_PRE,
        bcr.RELEASE_ROW_STATUS_FIELD: "ready",
        bcr.RELEASE_ROW_ERRORS_FIELD: [],
        "review_flags": [
            "manual reviewer addition: Pre concept added from corrected workbook",
        ],
        bcr.MANUAL_EDIT_TRAIL_FIELD: [{
            "kind": "addition",
            "at": round_stamp,
            "editor": owner_sub or "local:default",
            "pre_concept_id": pre_concept_id,
        }],
    }


def _refresh_edited_validation_reports(
    candidate: dict[str, Any],
) -> None:
    """Refresh frozen output audits when the exported Concept fields changed.

    The reports are content receipts, so retaining one after a reviewer edits
    ``concept_details`` would make the next readiness check compare new bytes
    with an old receipt. Routing-only question edits do not change the
    exported Concept projection and therefore keep their existing reports.
    """
    from . import katex_render_validation, source_asset_publication

    exported = {
        "records": candidate.get("records") or [],
        "chapter_meta": candidate.get("chapter_meta") or {},
    }
    checks = (
        (source_asset_publication, "inputs_sha256"),
        (katex_render_validation, "input_sha256"),
    )
    issues = list(candidate.get("issues") or [])
    for checker, digest_key in checks:
        old = candidate.get(checker.REPORT_FIELD)
        refreshed = (
            checker.inspect_assets(exported)
            if checker is source_asset_publication
            else checker.inspect_render(exported)
        )
        changed = (
            not isinstance(old, Mapping)
            or old.get(digest_key) != refreshed.get(digest_key)
            or old.get("version") != refreshed.get("version")
        )
        if not changed:
            continue
        candidate[checker.REPORT_FIELD] = refreshed
        phase = "release_assets" if checker is source_asset_publication else "render"
        issues = [
            issue for issue in issues
            if not isinstance(issue, Mapping) or issue.get("phase") != phase
        ]
        issues.extend(checker.release_findings(refreshed))
    candidate["issues"] = issues


def _sheet_headers(wb) -> dict[str, tuple]:
    return {
        name: tuple(
            next(wb[name].iter_rows(min_row=2, max_row=2, values_only=True),
                 ()),
        )
        for name in wb.sheetnames
    }


def _record_titles(record: Mapping[str, Any]) -> tuple[str, str]:
    topic = str(record.get("topic") or "").strip()
    title = str(
        record.get("concept_title") or record.get("concept") or ""
    ).strip()
    return topic, title


def _staged_maps(
    db: Session, job: models.UploadJob, payload: Mapping[str, Any]
) -> tuple[dict[str, int], dict[tuple[str, str], list[int]]]:
    """(tag -> record_index, (topic, title) -> [record_index...]).

    The tag map is rebuilt through ``transient_release_hierarchy`` — the
    exact function that rendered the downloaded workbook — so the ids
    here are byte-identical to the tags the reviewer's file carries. The
    transient pass skips defective rows, so its (concept, record) pairs
    are re-anchored to payload record indexes by equality, consumed in
    order (duplicate-safe).
    """

    records = payload.get("records") or []
    by_title: dict[tuple[str, str], list[int]] = {}
    for index, record in enumerate(records):
        if isinstance(record, Mapping):
            by_title.setdefault(_record_titles(record), []).append(index)

    tag_map: dict[str, int] = {}
    try:
        _chapter, concepts, carried, _defects = (
            release_files.transient_release_hierarchy(
                db, job, payload=dict(payload)
            )
        )
    except Exception:
        # The tag join is an assist; title matching still works. A
        # payload the hierarchy refuses outright will be refused again,
        # loudly, by the publication step below.
        return {}, by_title
    consumed: set[int] = set()
    for concept, record in zip(concepts, carried):
        if not isinstance(record, Mapping):
            continue
        key = _record_titles(record)
        index = next(
            (
                candidate for candidate in by_title.get(key, [])
                if candidate not in consumed
                and records[candidate] == record
            ),
            None,
        )
        if index is None:
            index = next(
                (
                    candidate for candidate in by_title.get(key, [])
                    if candidate not in consumed
                ),
                None,
            )
        if index is None:
            continue
        consumed.add(index)
        tag = str(getattr(concept, "machine_id", "") or "").strip()
        if tag and tag not in tag_map:
            tag_map[tag] = index
    return tag_map, by_title


def _workbook_rows(path: Path) -> list[dict[str, Any]]:
    """Every content row's topic/concept projection, layout-identified."""

    wb = openpyxl.load_workbook(path, data_only=True, read_only=True)
    try:
        if (
            "Released Concepts" in wb.sheetnames
            and str(wb["Released Concepts"].cell(1, 1).value or "")
            == "Release Row"
        ):
            ws = wb["Released Concepts"]
            headers = {
                str(value or "").strip().casefold(): index
                for index, value in enumerate(
                    next(ws.iter_rows(min_row=1, max_row=1, values_only=True), ())
                )
            }
            rows: list[dict[str, str]] = []
            for row_i, values in enumerate(
                ws.iter_rows(min_row=2, values_only=True), start=2
            ):
                if not values or not any(value not in (None, "") for value in values):
                    continue
                cell = lambda name: values[headers[name]] if headers.get(name, -1) < len(values) else ""
                raw_title = str(cell("concept title") or "")
                if not raw_title.strip():
                    continue
                rows.append({
                    "sheet": "Released Concepts",
                    "row": str(row_i),
                    "tag": identity.title_tag(raw_title),
                    "topic": str(cell("topic") or "").strip(),
                    "concept_title": strip_title_tag(raw_title).strip(),
                    "parent_concept": str(cell("parent concept") or "").strip(),
                    "concept_details": str(cell("concept details") or ""),
                    "concept_details_raw": str(cell("concept details") or ""),
                    "keywords": str(cell("keywords") or "").strip(),
                })
            return rows
        identified = layouts.identify_workbook(_sheet_headers(wb))
        rows: list[dict[str, str]] = []
        for found in identified.sheets:
            ws = wb[found.sheet_name]
            for row_i, row in enumerate(
                ws.iter_rows(min_row=3, values_only=True), start=3
            ):
                if row is None or not any(row):
                    continue
                top = found.sheet.block_values(row, "topic")
                con = found.sheet.block_values(row, "concept")
                raw_title = str(con.get("concept_title") or "")
                if not raw_title.strip():
                    continue
                rows.append({
                    "sheet": found.sheet_name,
                    "row": str(row_i),
                    "tag": identity.title_tag(raw_title),
                    "topic": strip_topic_title(
                        str(top.get("topic_title") or "")
                    ).strip(),
                    "concept_title": strip_title_tag(raw_title).strip(),
                    "parent_concept": str(
                        con.get("parent_concept") or ""
                    ).strip(),
                    "concept_details": str(
                        con.get("concept_details") or ""
                    ),
                    "concept_details_raw": str(
                        con.get("concept_details") or ""
                    ),
                    "keywords": str(con.get("keywords") or "").strip(),
                })
        from .concept_workbook_rows import coalesce_repeated_sheet_rows
        return coalesce_repeated_sheet_rows(rows)
    finally:
        wb.close()


_QUESTION_FIELDS = (
    "raw_task", "normalized_task", "polished_task", "frozen_task_text",
    "normalized_public_text", "question_text", "topic_hint", "options",
    "raw_solution_or_answer", "answer", "rationale",
)
_QUESTION_AUDIT_FIELDS = _QUESTION_FIELDS + (
    "shared_context", "source_context", "source_answer", "assets", "image_urls",
    "image_assets", "image_manifest", "images", "tables", "content_objects",
    "compound_subparts", "sub_questions", "requires_visual", "requires_context",
    "_image_captions", "reviewed_context", "learner_context",
    "generation_quality_policy", "source_task_polishing_policy",
)


def _question_workbook_rows(
    path: Path,
    *,
    payload: Mapping[str, Any] | None = None,
    concept_rows: list[dict[str, Any]] | None = None,
    lane: str = bcr.LANE_POST,
) -> list[dict[str, Any]] | None:
    """Read the optional complete question sheet from a review workbook.

    The diagnostic four-sheet workbook carries questions as ``example`` rows
    in ``Type Case Routing``. ``Source Questions`` remains accepted as a
    compatibility projection from an earlier build. The canonical three
    sheet Concept workbook carries reviewed question evidence in its
    Concept Details Types/Cases text and passes it through the model-owned
    author/critic adapter. A missing surface returns ``None`` (preserve
    questions); a present header-only surface returns ``[]`` (the reviewer
    intentionally selected an empty set).
    """

    wb = openpyxl.load_workbook(path, data_only=True, read_only=True)
    try:
        source_sheet = (
            "Source Questions" if "Source Questions" in wb.sheetnames
            else "Type Case Routing"
        )
        if source_sheet not in wb.sheetnames:
            # Pre questions are generated by the prerequisite pipeline and
            # are not part of the editable Pre Concept workbook. Preserve
            # that generated authority when a reviewer uploads the normal
            # three-sheet Pre file.
            if bcr.normalize_lane(lane) == bcr.LANE_PRE:
                return None
            # Canonical three-sheet Concept workbooks have no routing sheet.
            # Their Concept Details still carry the assembled Example text;
            # reconstruct a lossless review projection from the staged row's
            # immutable QID order and explicit ``Question label`` markers when
            # present.  This keeps the user editing the same file the UI
            # already downloads.
            return _canonical_detail_question_rows(
                payload, concept_rows, lane=lane
            )
        if source_sheet == "Type Case Routing" and bcr.normalize_lane(lane) == bcr.LANE_PRE:
            # A Type/Case routing surface is Post source-question input. Pre
            # Masters retain their generated prerequisite question bank.
            return None
        ws = wb[source_sheet]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            return []
        # ``build_release_workbook`` writes the headers in row 1.  Keep this
        # parser anchored to that contract; treating the first data row as a
        # header silently discarded/renamed question fields in edited files.
        header_values = rows[0]
        headers = {
            str(value or "").strip().casefold(): index
            for index, value in enumerate(header_values)
        }
        # Header row 1 is the standard workbook header.  A malformed custom
        # sheet is refused rather than interpreted by position.
        required = (
            {"row kind", "example qid", "example prompt"}
            if source_sheet == "Type Case Routing"
            else {"question id", "source qid", "question text"}
        )
        if not required.issubset(headers):
            raise WorkbookEditError(
                "the Source Questions sheet is missing one of the required "
                "identity/text columns"
            )

        def cell(values: tuple[Any, ...], name: str) -> Any:
            index = headers.get(name.casefold())
            return values[index] if index is not None and index < len(values) else ""

        out: list[dict[str, Any]] = []
        for row_number, values in enumerate(rows[1:], start=2):
            if not values or not any(value not in (None, "") for value in values):
                continue
            if source_sheet == "Type Case Routing":
                row_kind = str(cell(values, "Row Kind") or "").strip().lower()
                if row_kind not in {"example", "reviewer_added"}:
                    continue
                question_id = str(cell(values, "Example QID") or "").strip()
                source_qid = question_id if row_kind == "example" else ""
                kind = "reviewer_added" if row_kind == "reviewer_added" else "source"
                text = str(cell(values, "Example Prompt") or "")
                raw_task = ""
                public_text = ""
                options_raw = ""
                topic_hint = str(cell(values, "Owner Topic IDs") or "")
                source_label = str(cell(values, "Case ID") or "")
                provenance = kind
            else:
                kind = str(cell(values, "Question Kind") or "source").strip().lower()
                question_id = str(cell(values, "Question ID") or "").strip()
                source_qid = str(cell(values, "Source QID") or "").strip()
                text = str(cell(values, "Question Text") or "")
                raw_task = str(cell(values, "Raw Task") or "")
                public_text = str(cell(values, "Normalized Public Text") or "")
                options_raw = cell(values, "Options")
                topic_hint = str(cell(values, "Topic") or "")
                source_label = str(cell(values, "Source Label") or "")
                provenance = str(cell(values, "Provenance") or kind).strip()
            options: Any = options_raw
            if isinstance(options_raw, str) and options_raw.strip():
                try:
                    options = json.loads(options_raw)
                except (TypeError, ValueError):
                    # Preserve reviewer text; the Master contract can name a
                    # malformed options shape during its own validation.
                    options = options_raw
            out.append({
                "row": row_number,
                "kind": kind,
                "question_id": question_id,
                "source_qid": source_qid,
                "source_label": source_label,
                "topic_hint": topic_hint,
                "question_text": text,
                "raw_task": raw_task,
                "normalized_public_text": public_text,
                "options": options,
                "raw_solution_or_answer": str(cell(values, "Source Answer") or ""),
                "provenance": provenance,
            })
        return out
    finally:
        wb.close()


def _canonical_detail_question_rows(
    payload: Mapping[str, Any] | None,
    concept_rows: list[dict[str, Any]] | None,
    *,
    lane: str = bcr.LANE_POST,
) -> list[dict[str, Any]] | None:
    """The API owns edited question identity, membership and placement.

    Pre concepts feed automatic prerequisite authoring; their examples are
    not a manually authored bank. A Post upload is reconciled from the
    complete actual Concept Details, without positional or regex identity.
    """
    if payload is None or concept_rows is None or bcr.normalize_lane(lane) == bcr.LANE_PRE:
        return None
    # Equality of the complete recorded question-bearing cells is a no-op
    # proof, not an inference about their meaning. A renamed/moved/changed
    # cell falls through to the model with the complete original bank.
    from collections import Counter
    def cell_key(row):
        return (
            str(row.get("topic") or ""),
            str(row.get("concept_title") or row.get("concept") or ""),
            str(row.get("concept_details") or row.get("concept_description") or ""),
        )
    if Counter(cell_key(row) for row in concept_rows) == Counter(
        cell_key(row) for row in payload.get("records") or []
        if isinstance(row, Mapping)
    ):
        return None
    from .concept_question_review import review_canonical_questions
    from .reviewed_question_set import ReviewedQuestionSetError
    try:
        return review_canonical_questions(payload, concept_rows)
    except ReviewedQuestionSetError as exc:
        raise WorkbookEditError(str(exc)) from exc


def _question_identity(row: Mapping[str, Any]) -> str:
    return str(
        row.get("qid") or row.get("source_qid") or row.get("question_id")
        or row.get("pre_question_id") or ""
    ).strip()


def _reviewer_question_id(row: Mapping[str, Any], used: set[str]) -> str:
    """Mint a repeatable reviewer-added ID from the row's authored content."""

    basis = json.dumps({
        key: row.get(key) for key in (
            "question_text", "raw_task", "normalized_public_text",
            "options", "topic_hint", "raw_solution_or_answer",
        )
    }, ensure_ascii=False, sort_keys=True, default=str)
    prefix = "QREV-" + hashlib.sha256(basis.encode("utf-8")).hexdigest()[:16]
    candidate = prefix
    suffix = 2
    while candidate in used:
        candidate = f"{prefix}-{suffix}"
        suffix += 1
    return candidate


def _canonical_review_route_rows(
    parsed: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Project model-reviewed Concept rows onto the existing route shape.

    The canonical three-sheet workbook has no ``Type Case Routing`` tab.  Its
    author adapter still returns the reviewed Type/Case/Concept target for
    each accepted question.  Reusing the existing route reconciliation keeps
    that target in the staged snapshot, including intentional moves and
    omissions, without inventing a second workbook contract.
    """

    rows: list[dict[str, Any]] = []
    for row in parsed:
        if not isinstance(row, Mapping):
            continue
        source_qid = str(row.get("source_qid") or "").strip()
        kind = "reviewer_added" if str(row.get("kind") or "").strip().lower() == "reviewer_added" else "example"
        rows.append({
            "row_kind": kind,
            "type_id": str(row.get("type_id") or "").strip(),
            "type_title": str(row.get("type_title") or ""),
            "type_definition": str(row.get("type_definition") or ""),
            "case_id": str(row.get("case_id") or "").strip(),
            "case_definition": str(row.get("case_definition") or ""),
            "owner_topic_ids": [str(row.get("topic_hint") or "").strip()]
            if str(row.get("topic_hint") or "").strip() else [],
            "qids": [source_qid] if source_qid else [],
            "example_qid": source_qid,
            "example_prompt": str(row.get("question_text") or ""),
            "example_number": row.get("concept_row_index"),
            "audit_status": "ready",
            "error": "",
        })
    return rows


def _apply_question_review(
    payload: dict[str, Any],
    parsed: list[dict[str, Any]],
    *,
    lane: str,
) -> list[dict[str, Any]]:
    """Replace the reviewed question set while retaining a complete audit.

    The reviewer owns the reviewed set: omission is a recorded disposition,
    additions receive a stable ``QREV-*`` identity, and original Post QIDs
    are never silently rewritten.  The resulting inventory is exactly what
    the Post Master receives on its next build.
    """

    canonical_reconciled: dict[str, Any] | None = None
    canonical_receipt = getattr(parsed, "receipt", None)
    canonical_added_ids: list[str] = []
    # ``ReviewRows`` carries a receipt even for the intentional all-omitted
    # result.  Test presence rather than truthiness so an empty receipt still
    # records the reviewed set and cannot fall back to the original bank.
    if canonical_receipt is not None and lane == bcr.LANE_POST:
        # The model-owned adapter has already checked exact edited-text
        # quotes and closed-world source dispositions.  Reconcile its route
        # projection with the existing release revision helper so the same
        # accepted Type/Case/Concept placement reaches the Master snapshot.
        from .reviewed_question_set import (
            ReviewedQuestionSetError,
            reconcile_post_review,
        )
        try:
            canonical_reconciled = reconcile_post_review(
                payload, _canonical_review_route_rows(parsed)
            )
        except ReviewedQuestionSetError as exc:
            raise WorkbookEditError(str(exc)) from exc
        canonical_added_ids = list(
            (canonical_reconciled.get("review_question_audit") or {}).get("added")
            or []
        )

    if lane == bcr.LANE_PRE:
        original = [
            copy.deepcopy(row) for row in payload.get("generated_questions") or []
            if isinstance(row, Mapping)
        ]
    else:
        inventory = payload.get("question_task_inventory") or {}
        original = [
            copy.deepcopy(row) for row in inventory.get("items") or []
            if isinstance(row, Mapping)
        ]
    original_by_id = {_question_identity(row): row for row in original}
    if "" in original_by_id:
        original_by_id.pop("", None)
    if len(original_by_id) != len(original):
        raise WorkbookEditError(
            "the staged question input contains a missing or duplicate identity"
        )
    selected: list[dict[str, Any]] = []
    seen: set[str] = set()
    operations: list[dict[str, Any]] = []
    omitted: list[str] = []
    added: list[str] = []
    moved: list[dict[str, str]] = []
    edited: list[dict[str, Any]] = []
    integrity_conflicts: list[str] = []
    canonical_added_index = 0
    for row in parsed:
        if row.get("integrity_conflict"):
            integrity_conflicts.append(str(row["integrity_conflict"]))
        question_id = str(row.get("question_id") or "").strip()
        source_qid = str(row.get("source_qid") or "").strip()
        identity = source_qid or question_id
        kind = str(row.get("kind") or "source").strip().lower()
        if kind == "reviewer_added" or (not identity and row.get("question_text")):
            if canonical_reconciled is not None and canonical_added_index < len(canonical_added_ids):
                identity = str(canonical_added_ids[canonical_added_index])
                canonical_added_index += 1
            else:
                identity = _reviewer_question_id(row, set(original_by_id) | seen)
            kind = "reviewer_added"
        if not identity:
            raise WorkbookEditError(
                f"Source Questions row {row.get('row')} has no question identity"
            )
        if identity in seen:
            raise WorkbookEditError(
                f"Source Questions row {row.get('row')} repeats question {identity!r}"
            )
        # A source row whose visible id was altered may only be an explicit
        # reviewer addition.  This keeps original identities immutable while
        # allowing the requested omit/add workflow.
        if (
            kind != "reviewer_added"
            and question_id in original_by_id
            and not source_qid
            and lane == bcr.LANE_POST
        ):
            raise WorkbookEditError(
                f"Source Questions row {row.get('row')} omits the immutable "
                f"source QID for question {question_id!r}"
            )
        if identity not in original_by_id and kind != "reviewer_added":
            raise WorkbookEditError(
                f"Source Questions row {row.get('row')} names unknown source "
                f"question {identity!r}; mark intentional additions as reviewer_added"
            )
        if lane == bcr.LANE_POST and kind == "reviewer_added":
            source_qid = ""
        if identity in original_by_id:
            current = copy.deepcopy(original_by_id[identity])
            before_topic = str(current.get("topic_hint") or "")
        else:
            current = {
                "qid": identity,
                "source_kind": "reviewer_added",
                "source_label": str(row.get("source_label") or "Reviewer added"),
                "provenance": "reviewer_added",
                "reviewer_added": True,
                "raw_task": "",
            }
            before_topic = ""
            added.append(identity)
        before_values = {
            key: copy.deepcopy(current.get(key)) for key in _QUESTION_AUDIT_FIELDS
        }
        from . import generation_quality_policy as quality
        from . import source_task_polishing_policy as source_format
        if lane == bcr.LANE_POST and quality.active(row):
            current.update(quality.fields(row))
            # This is a newly accepted, explicitly reviewed source task. Its
            # quote and separate context, including an empty context, are the
            # same authority later passed to the frozen Master.
            current[source_format.FIELD] = source_format.VERSION
            current.setdefault("frozen_task_text", str(current.get("raw_task") or ""))
        original_raw = str(current.get("raw_task") or "")
        original_normalized = str(current.get("normalized_task") or "")
        original_polished = str(current.get("polished_task") or "")
        original_frozen = str(current.get("frozen_task_text") or "")
        preserve_dependencies = bool(row.get("preserve_source_dependencies"))
        for key in _QUESTION_FIELDS:
            value = row.get(key)
            if key == "question_text" and not value:
                continue
            if key == "options" and not value and preserve_dependencies:
                # The model returns ``options=[]`` when the reviewer did not
                # replace the source option set.  Keep the immutable source
                # options in that case; an empty replacement is applied only
                # when the verdict explicitly drops its dependencies.
                continue
            if value in (None, "") and key not in {"raw_task", "normalized_public_text", "question_text", "topic_hint"}:
                continue
            if key == "question_text":
                # ``question_text`` is the review-facing wording.  The
                # assessment snapshot consumes ``raw_task`` for source
                # question authoring, so carry the edited wording into that
                # field even when the workbook also displays the old raw
                # task.  A dedicated Raw Task edit below remains authoritative
                # when the reviewer intentionally supplies both values.
                current["raw_task"] = str(value)
                current[key] = str(value)
            elif key == "options":
                if not isinstance(value, list):
                    raise WorkbookEditError(
                        f"Source Questions row {row.get('row')} has malformed options"
                    )
                current[key] = copy.deepcopy(value)
            else:
                current[key] = str(value)
        if "shared_context" in row:
            context = str(row.get("shared_context") or "")
            if context or not preserve_dependencies:
                current["shared_context"] = context
        if "raw_solution_or_answer" in row:
            answer = str(row.get("raw_solution_or_answer") or "")
            if answer or not preserve_dependencies:
                current["raw_solution_or_answer"] = answer
        if not isinstance(row.get("context_review"), Mapping) and not preserve_dependencies and (
            "shared_context" in row
            or "raw_solution_or_answer" in row
            or "options" in row
        ):
            # A replacement verdict owns the supporting source fields too;
            # do not let an older nested source_context resurrect the prior
            # answer/context/options during Master materialization. Assets
            # and other source evidence remain copied unless the review model
            # explicitly supplied a replacement for them.
            # The accepted wording is the active replacement.  Clear
            # source-owned dependency projections copied from the immutable
            # item so the Master source atom cannot resurrect an old figure,
            # table, compound child, or visual context after an explicit
            # replacement verdict.  The original values remain in
            # ``original_source_questions``/revision history for provenance.
            for dependency in (
                "assets", "image_urls", "image_assets", "image_manifest",
                "images", "tables", "content_objects", "compound_subparts",
                "sub_questions", "requires_visual", "requires_context",
                "_image_captions",
            ):
                current.pop(dependency, None)
            current["source_context"] = {
                "source_answer": str(current.get("raw_solution_or_answer") or ""),
                "shared_context": str(current.get("shared_context") or ""),
                "options": copy.deepcopy(current.get("options") or []),
            }
        reviewed_target = {
            "concept_row_index": row.get("concept_row_index"),
            "concept_title": str(row.get("concept_title") or ""),
            "topic": str(row.get("topic_hint") or ""),
            "placement_section": str(row.get("placement_section") or ""),
            "type_id": str(row.get("type_id") or ""),
            "type_title": str(row.get("type_title") or ""),
            "type_definition": str(row.get("type_definition") or ""),
            "case_id": str(row.get("case_id") or ""),
            "case_definition": str(row.get("case_definition") or ""),
            "preserve_source_dependencies": preserve_dependencies,
            **({
                "context_review": copy.deepcopy(row["context_review"]),
                "removed_dependencies": copy.deepcopy(row.get("removed_dependencies") or []),
                "concept_details_sha256": row.get("concept_details_sha256"),
            } if isinstance(row.get("context_review"), Mapping) else {}),
        }
        if any(value not in (None, "", []) for value in reviewed_target.values()):
            current["_aegis_reviewed_target"] = reviewed_target
            current["reviewed_type_id"] = reviewed_target["type_id"]
            current["reviewed_case_id"] = reviewed_target["case_id"]
            current["reviewed_concept_title"] = reviewed_target["concept_title"]
            current["reviewed_concept_row_index"] = reviewed_target["concept_row_index"]
            current["placement_section"] = reviewed_target["placement_section"]
        # The workbook's Example Prompt/Question Text is the review-facing
        # wording.  Carry it into every downstream wording field consumed by
        # source-atom construction.  A separately edited Raw Task cell wins
        # when it differs from the downloaded value; otherwise the visible
        # reviewer wording is authoritative.  Frozen polished source tasks
        # receive the same explicit correction so the source-format policy
        # cannot resurrect stale wording during Master freeze.
        visible_text = str(row.get("question_text") or "")
        supplied_raw = str(row.get("raw_task") or "")
        raw_was_edited = bool(supplied_raw and supplied_raw != original_raw)
        if visible_text.strip() and not raw_was_edited:
            current["raw_task"] = visible_text
            current["normalized_task"] = visible_text
            current["polished_task"] = visible_text
            if original_frozen:
                current["frozen_task_text"] = visible_text
            current["normalized_public_text"] = visible_text
        elif raw_was_edited:
            current["normalized_task"] = supplied_raw
            current["polished_task"] = supplied_raw
            if original_frozen:
                current["frozen_task_text"] = supplied_raw
            current["normalized_public_text"] = supplied_raw
        if quality.active(current):
            # Dedicated complete-question/Example edits have no separately
            # reviewed context field. The edited wording is their complete
            # authority; the canonical API path sets accepted context below.
            effective = str(current.get("frozen_task_text") or current.get("raw_task") or "")
            previous = original_frozen or original_polished or original_normalized or original_raw
            if effective != previous:
                current["learner_context"] = ""
            if source_format.applies(current):
                current["frozen_task_text"] = str(current.get("raw_task") or "")
        if not str(current.get("raw_task") or current.get("question_text") or "").strip():
            raise WorkbookEditError(
                f"Source Questions row {row.get('row')} has no question text"
            )
        from .concept_review_context import apply_support_decisions
        apply_support_decisions(current, row)
        if str(current.get("topic_hint") or "") != before_topic and identity in original_by_id:
            moved.append({"identity": identity, "from": before_topic, "to": str(current.get("topic_hint") or "")})
        changed_fields = [
            key for key in _QUESTION_AUDIT_FIELDS
            if before_values.get(key) != current.get(key)
        ]
        if changed_fields:
            edited.append({
                "identity": identity,
                "fields": changed_fields,
                "before": before_values,
                "after": {key: copy.deepcopy(current.get(key)) for key in _QUESTION_AUDIT_FIELDS},
            })
        current.setdefault("qid", identity)
        current["_review_identity"] = identity
        selected.append(current)
        seen.add(identity)
    omitted = [identity for identity in original_by_id if identity not in seen]
    if lane == bcr.LANE_POST:
        inventory = copy.deepcopy(dict(payload.get("question_task_inventory") or {}))
        inventory["items"] = selected
        inventory.setdefault("reviewed_source_questions", {})
        inventory["reviewed_source_questions"] = {
            "version": "reviewed-source-questions-1",
            "original_ids": list(original_by_id),
            "reviewed_ids": list(seen),
            "omitted": omitted,
            "added": added,
            "moved": moved,
            "edited": edited,
            "integrity_conflicts": integrity_conflicts,
            "reviewed_at": datetime.now(timezone.utc).isoformat(),
        }
        payload["question_task_inventory"] = inventory
        if canonical_reconciled is not None:
            # Preserve the existing Type/Case rows (including their edited
            # definitions) while replacing only the accepted Example set.
            # This is the same route projection used by the legacy review
            # revision helper and is what the Master source snapshot reads.
            payload["type_case_rows"] = copy.deepcopy(
                canonical_reconciled.get("type_case_rows") or []
            )
    else:
        payload["generated_questions"] = selected
    payload.setdefault("review_question_audit", {})
    payload["review_question_audit"] = {
        "version": "reviewed-source-questions-1",
        "lane": lane,
        "original_ids": list(original_by_id),
        "reviewed_ids": list(seen),
        "omitted": omitted,
        "added": added,
        "moved": moved,
        "edited": edited,
        "integrity_conflicts": integrity_conflicts,
        "reviewed_at": datetime.now(timezone.utc).isoformat(),
    }
    if canonical_reconciled is not None:
        helper_audit = canonical_reconciled.get("review_question_audit") or {}
        # The helper owns route membership/dispositions; retain the richer
        # field-level audit assembled above and attach the complete author /
        # critic receipt, including the explicit all-omitted case.
        for key in ("original_ids", "reviewed_ids", "omitted", "added", "moved"):
            if key in helper_audit:
                payload["review_question_audit"][key] = copy.deepcopy(helper_audit[key])
        payload["review_question_audit"]["model_review_receipt"] = copy.deepcopy(
            dict(canonical_receipt or {})
        )
        payload["review_question_audit"]["model_review_policy"] = str(
            dict(canonical_receipt or {}).get("policy") or ""
        )
    if lane == bcr.LANE_POST:
        payload.setdefault("question_task_inventory", {})[
            "reviewed_source_questions"
        ] = copy.deepcopy(payload["review_question_audit"])
    return operations + [{"kind": "question_review", **payload["review_question_audit"]}]


def apply_workbook_and_publish(
    db: Session,
    job: models.UploadJob,
    *,
    lane: str,
    workbook_path: Path,
    owner_sub: str = "",
) -> dict[str, Any]:
    """One recorded round of workbook edits, then the CMS publication."""

    db.refresh(job)
    generation_recovery.require_mutation_allowed(
        job, operation="upload and publish an edited workbook"
    )

    lane = bcr.normalize_lane(lane)
    payload = bcr.release_payload(job, lane=lane)
    if payload is None:
        raise WorkbookEditError(
            "this job has no staged release for this lane; generate and "
            "stage the release before uploading an edited workbook"
        )
    try:
        parsed = _workbook_rows(workbook_path)
    except WorkbookLayoutError as error:
        raise WorkbookEditError(
            "the uploaded file is not a canonical Concept workbook: "
            + str(error)
        ) from error
    if not parsed:
        raise WorkbookEditError(
            "the uploaded workbook carries no concept rows"
        )

    tag_map, by_title = _staged_maps(db, job, payload)
    records = payload.get("records") or []
    edits: list[dict[str, Any]] = []
    unmatched: list[str] = []
    matched_rows = 0
    consumed: set[int] = set()
    for row in parsed:
        index: int | None = None
        if row["tag"] and row["tag"] in tag_map:
            index = tag_map[row["tag"]]
        else:
            index = next(
                (
                    candidate for candidate in by_title.get(
                        (row["topic"], row["concept_title"]), []
                    )
                    if candidate not in consumed
                ),
                None,
            )
        if index is None or not isinstance(records[index], Mapping):
            unmatched.append(
                f"{row['sheet']!r} row {row['row']}: "
                f"{row['concept_title']!r} matches no staged concept"
            )
            continue
        consumed.add(index)
        matched_rows += 1
        record = records[index]
        for field in sorted(release_review.EDITABLE_FIELDS):
            after = str(row.get(field, "")).strip()
            if field == "concept_details":
                after = str(row.get(field, ""))
            current = str(
                record.get(field)
                or (record.get("concept") if field == "concept_title"
                    else "")
                or (record.get("concept_description")
                    if field == "concept_details" else "")
                or ""
            )
            if field in ("topic", "concept_title") and not after:
                # The workbook cell is blank (merged-cell rendering);
                # never treat that as "empty the field".
                continue
            if after == current or (not after and not current.strip()):
                continue
            edits.append({
                "record_index": index,
                "field": field,
                "before": current,
                "after": after,
            })
    if unmatched:
        raise WorkbookEditError(
            "refusing the upload — these workbook rows match no staged "
            "concept (a new concept is added on the review page, not by "
            "workbook row): " + "; ".join(unmatched[:10])
        )

    round_applied = False
    if edits:
        release_review.apply_manual_edits(
            db, job,
            lane=lane,
            staged_release_uid=str(
                payload.get(bcr.STAGED_RELEASE_UID_FIELD) or ""
            ),
            edits=edits,
            owner_sub=owner_sub,
        )
        round_applied = True

    from . import build_concepts_release_publication as publication

    published = publication.upload_release_to_database(
        db, int(job.id), owner_sub=owner_sub or None, lane=lane
    )
    return {
        "lane": lane,
        "workbook_rows": len(parsed),
        "matched_rows": matched_rows,
        "changed_fields": len(edits),
        "round_recorded": round_applied,
        "publication": published,
    }


def apply_workbook_for_review(
    db: Session,
    job: models.UploadJob,
    *,
    lane: str,
    workbook_path: Path,
    owner_sub: str = "",
) -> dict[str, Any]:
    """Apply a complete corrected Concept input without publishing it.

    This is the Q41 handoff: one validated workbook round replaces the
    current staged Concept draft, then a later Master action reads that exact
    draft.  Concept edits and the optional Source Questions set commit as one
    immutable ``ConceptReleaseVersion`` round, so a malformed workbook cannot
    partially overwrite the slot.
    """

    db.refresh(job)
    generation_recovery.require_mutation_allowed(
        job, operation="upload corrected Concept inputs"
    )
    lane = bcr.normalize_lane(lane)
    payload = bcr.release_payload(job, lane=lane)
    if payload is None:
        raise WorkbookEditError(
            "this job has no staged release for this lane; generate the "
            "Concept files before uploading corrections"
        )
    try:
        parsed = _workbook_rows(workbook_path)
    except WorkbookLayoutError as error:
        raise WorkbookEditError(
            "the uploaded file is not a canonical Concept workbook: " + str(error)
        ) from error
    raw_records = payload.get("records")
    records = (
        copy.deepcopy(raw_records)
        if isinstance(raw_records, list)
        else []
    )
    if not parsed and records:
        raise WorkbookEditError(
            "the corrected workbook carries no Concept rows; refusing to "
            "silently drop staged concepts"
        )
    tag_map, by_title = _staged_maps(db, job, payload)
    concept_edits: list[dict[str, Any]] = []
    additions: list[dict[str, Any]] = []
    if lane == bcr.LANE_PRE:
        for index, record in enumerate(records):
            if not isinstance(record, Mapping):
                continue
            alias = str(record.get("_reviewed_pre_identity_tag") or "").strip()
            if not alias:
                continue
            if alias in tag_map and tag_map[alias] != index:
                raise WorkbookEditError(
                    "a previously reviewed Pre identity now refers to two concepts; "
                    "download the current Concept file before applying further edits"
                )
            tag_map[alias] = index
    matched_indices: set[int] = set()
    consumed: set[int] = set()
    bound_indices: dict[int, int] = {}
    unmatched: list[str] = []
    # Pre additions are minted only after every existing row has been bound;
    # this makes allocation independent of workbook row order and guarantees
    # that no new row can consume an existing record by position.
    addition_rows: list[dict[str, Any]] = []
    for row in parsed:
        index: int | None = None
        if row["tag"] and row["tag"] in tag_map:
            index = tag_map[row["tag"]]
        elif (
            row["tag"]
            and not (
                lane == bcr.LANE_PRE
                and _is_expected_pre_tag(db, payload, row["tag"])
            )
        ):
            # An Aegis identity claim cannot be rescued by a title fallback:
            # that would turn a stale/foreign id into an edit of whichever
            # row happens to share its current display text.
            index = None
        elif not row["tag"]:
            index = next(
                (
                    candidate for candidate in by_title.get(
                        (row["topic"], row["concept_title"]), []
                    )
                    if candidate not in consumed
                ),
                None,
            )
        else:
            # A chapter/lane tag that is not in ``tag_map`` is an addition
            # hint, never a fallback to a same-title existing row.
            index = None
        # A tag outside this job's chapter/lane identity is an identity claim
        # and must remain a loud refusal. Corrected catalogue workbooks may
        # carry this job's own chapter/lane tag even when the original staged
        # Pre capture was empty; that tag is display metadata for the explicit
        # addition (its text is removed by ``strip_title_tag``).
        if (
            index is None
            and row["tag"]
            and not (
                lane == bcr.LANE_PRE
                and _is_expected_pre_tag(db, payload, row["tag"])
            )
        ):
            unmatched.append(
                f"{row['sheet']!r} row {row['row']}: stale or foreign "
                f"staged concept identity {row['tag']!r}"
            )
            continue
        if index is not None and index in consumed:
            unmatched.append(
                f"{row['sheet']!r} row {row['row']}: duplicate staged concept identity"
            )
            continue
        if index is None or not isinstance(records[index], Mapping):
            if lane == bcr.LANE_PRE:
                # Explicit reviewer additions are allowed in Pre, including
                # an empty original capture. They carry authored cells only;
                # no title/topic similarity or row position is used to bind
                # them to an old record.
                if not str(row.get("topic") or "").strip():
                    unmatched.append(
                        f"{row['sheet']!r} row {row['row']}: added Pre concept "
                        "has no topic"
                    )
                elif not str(row.get("concept_title") or "").strip():
                    unmatched.append(
                        f"{row['sheet']!r} row {row['row']}: added Pre concept "
                        "has no concept title"
                    )
                else:
                    addition_rows.append(row)
                continue
            unmatched.append(
                f"{row['sheet']!r} row {row['row']}: {row['concept_title']!r}"
            )
            continue
        consumed.add(index)
        matched_indices.add(index)
        bound_indices[id(row)] = index
        record = records[index]
        for field in sorted(release_review.EDITABLE_FIELDS):
            after = str(row.get(field, ""))
            if field == "concept_details":
                after = str(row.get(field, ""))
            else:
                after = after.strip()
            current = str(
                record.get(field)
                or (record.get("concept") if field == "concept_title" else "")
                or (record.get("concept_description") if field == "concept_details" else "")
                or ""
            )
            if field in ("topic", "concept_title") and not after:
                raise WorkbookEditError(
                    f"{row['sheet']!r} row {row['row']}: {field} may not be empty"
                )
            if after != current:
                concept_edits.append({
                    "record_index": index,
                    "field": field,
                    "before": current,
                    "after": after,
                })
    if lane == bcr.LANE_PRE and addition_rows:
        round_stamp = datetime.now(timezone.utc).isoformat()
        new_ids = _fresh_pre_concept_ids(records, len(addition_rows))
        for row, pre_concept_id in zip(addition_rows, new_ids):
            index = len(records)
            records.append(_new_pre_record(
                row,
                pre_concept_id,
                round_stamp=round_stamp,
                owner_sub=owner_sub,
            ))
            additions.append({
                "record_index": index,
                "pre_concept_id": pre_concept_id,
                "topic": str(row.get("topic") or "").strip(),
                "concept_title": str(row.get("concept_title") or "").strip(),
                "concept_details": str(row.get("concept_details") or ""),
                "keywords": str(row.get("keywords") or "").strip(),
                "workbook_identity_tag": str(row.get("tag") or "").strip(),
                "source": "reviewer_workbook",
            })
    if unmatched:
        raise WorkbookEditError(
            "refusing the upload — workbook rows match no staged concept: "
            + "; ".join(unmatched[:10])
        )
    original_record_count = len(records) - len(additions)
    if original_record_count and matched_indices != set(range(original_record_count)):
        missing = sorted(set(range(original_record_count)) - matched_indices)
        raise WorkbookEditError(
            "refusing the upload — corrected Concept input omitted staged "
            "record(s): " + ", ".join(str(value + 1) for value in missing[:20])
        )

    # Mechanical concept identity validation runs before the model-owned
    # canonical question review.  An invalid workbook therefore cannot cause
    # provider spend.  The adapter's edited row index is then rebound to the
    # staged record index used by the immutable Master snapshot, so row order
    # changes in Excel cannot shift a reviewed question onto another Concept.
    try:
        question_rows = _question_workbook_rows(
            workbook_path, payload=payload, concept_rows=parsed, lane=lane
        )
    except WorkbookEditError:
        raise
    if question_rows is not None:
        for question in question_rows:
            try:
                source_index = int(question.get("concept_row_index"))
            except (TypeError, ValueError):
                continue
            if 0 <= source_index < len(parsed):
                question["concept_row_index"] = bound_indices.get(
                    id(parsed[source_index]), source_index
                )

    # Validate the entire question replacement against a copy before any
    # version row or slot is written.  An absent sheet means no question
    # corrections and preserves the current set for compatibility with older
    # review workbooks.
    candidate = copy.deepcopy(payload)
    # ``records`` is a validated working copy.  In particular, assigning it
    # here matters for an empty staged list: ``payload.get('records') or []``
    # would otherwise append additions to a detached temporary list.
    candidate["records"] = copy.deepcopy(records)
    question_operations: list[dict[str, Any]] = []
    if question_rows is not None:
        question_operations = _apply_question_review(
            candidate, question_rows, lane=lane
        )
        audit = candidate.get("review_question_audit") or {}
        if any(audit.get(key) for key in (
            "edited", "omitted", "added", "moved", "integrity_conflicts"
        )):
            issues = list(candidate.get("issues") or [])
            issues.append({
                "severity": "warning",
                "code": "reviewer_source_question_override",
                "phase": "concept_review",
                "message": (
                    "The reviewer supplied the authoritative reviewed question "
                    "set; original source provenance remains in the immutable "
                    "review history."
                ),
                "details": copy.deepcopy(audit),
            })
            candidate["issues"] = issues
    # Apply concept operations to the candidate in the same mechanics as the
    # existing review service.  This keeps the downloaded values authoritative
    # and avoids an edit round being committed before question validation.
    round_stamp = datetime.now(timezone.utc).isoformat()
    all_operations = list(question_operations)
    for edit in concept_edits:
        index = int(edit["record_index"])
        row = candidate["records"][index]
        field = str(edit["field"])
        row[field] = str(edit["after"])
        trail = row.setdefault(release_review.MANUAL_EDIT_TRAIL_FIELD, [])
        trail.append({
            "field": field,
            "at": round_stamp,
            "editor": owner_sub or "local:default",
        })
        flags = row.setdefault("review_flags", [])
        note = f"manual reviewer edit: {field} replaced in place"
        if note not in flags:
            flags.append(note)
        all_operations.append(dict(edit))
    all_operations.extend({
        "kind": "concept_addition",
        **addition,
    } for addition in additions)
    if not concept_edits and not question_operations and not additions:
        return {
            "lane": lane,
            "workbook_rows": len(parsed),
            "question_rows": len(question_rows or []),
            "matched_rows": len(matched_indices),
            "added_rows": 0,
            "changed_fields": 0,
            "round_recorded": False,
            "review": release_review.review_view(db, job, lane),
        }

    if question_rows is not None:
        from .reviewed_question_set import ReviewedQuestionSetError, synchronize_reviewed_catalog
        try:
            synchronize_reviewed_catalog(candidate, question_rows)
        except ReviewedQuestionSetError as exc:
            raise WorkbookEditError(str(exc)) from exc
    # A corrected Pre workbook is an explicit reviewer revision.  Adopt the
    # current foundation-policy stamp on this new staged payload only; the
    # original sealed envelope and prior release version remain immutable.
    # The marker gives the regeneration contract a durable join for the exact
    # release it must rebuild, including the uploaded file receipt.
    if lane == bcr.LANE_PRE and (concept_edits or additions):
        from . import prelearning_foundation_policy

        try:
            workbook_sha256 = hashlib.sha256(
                workbook_path.read_bytes()
            ).hexdigest()
        except OSError:
            workbook_sha256 = ""
        candidate[prelearning_foundation_policy.KEY] = (
            prelearning_foundation_policy.VERSION
        )
        candidate["_reviewed_pre_input"] = {
            "version": "reviewed-pre-input-1",
            "policy_key": prelearning_foundation_policy.KEY,
            "policy_version": prelearning_foundation_policy.VERSION,
            "parent_release_uid": str(
                payload.get(bcr.STAGED_RELEASE_UID_FIELD) or ""
            ),
            "workbook_filename": workbook_path.name,
            "workbook_sha256": workbook_sha256,
            "accepted_at": datetime.now(timezone.utc).isoformat(),
            "added_pre_concept_ids": [
                str(item.get("pre_concept_id") or "")
                for item in additions
            ],
            "workbook_identity_tags": [
                str(item.get("workbook_identity_tag") or "")
                for item in additions
            ],
        }
        if additions and original_record_count == 0:
            # The reviewer has explicitly replaced the empty capture with
            # authored rows. Retire only its empty-capture diagnostics; a
            # source-integrity refusal or unreadable snapshot stays visible.
            retired_codes = {
                "pre_learning_empty_capture_verdict",
                "pre_learning_empty_capture_review_flag",
            }
            retired_issues = [
                copy.deepcopy(issue) for issue in candidate.get("issues") or []
                if isinstance(issue, Mapping) and issue.get("code") in retired_codes
            ]
            candidate["_reviewed_pre_superseded"] = {
                "reason": "The reviewer supplied concepts in the corrected Pre workbook.",
                "pre_lane_verdict": copy.deepcopy(
                    candidate.get(bcr.PRE_LANE_VERDICT_FIELD) or {}
                ),
                "issues": retired_issues,
            }
            candidate[bcr.PRE_LANE_VERDICT_FIELD] = {}
            candidate["issues"] = [
                issue for issue in candidate.get("issues") or []
                if not isinstance(issue, Mapping) or issue.get("code") not in retired_codes
            ]
        candidate[bcr.STAGED_ROW_DEFECTS_FIELD] = bcr.staged_row_defects(
            candidate.get("records") or []
        )
    if concept_edits or additions:
        _refresh_edited_validation_reports(candidate)
    candidate["summary"] = bcr._release_summary(
        [row for row in candidate.get("records") or [] if isinstance(row, Mapping)],
        list(candidate.get("issues") or []),
    )
    # ``_commit_round`` mints uid/version and stores the complete pre/post
    # payload. The current UID is read from the slot at the transaction
    # boundary. Canonical workbooks do not embed a revision UID: the submitted
    # cells are the requested replacement, and the model reviews them against
    # the current bank. Title tags verify Concept identity, not file freshness.
    current_uid = str(payload.get(bcr.STAGED_RELEASE_UID_FIELD) or "")
    release_review._seed_history(db, job, lane, owner_sub)
    release_review._commit_round(
        db, job, lane, candidate,
        origin="manual_edit",
        owner_sub=owner_sub,
        instruction="Uploaded corrected Concept inputs",
        operations=all_operations,
        diff={
            "changes": concept_edits,
            "additions": copy.deepcopy(additions),
            "question_review": copy.deepcopy(candidate.get("review_question_audit") or {}),
        },
        parent_uid=current_uid,
    )
    return {
        "lane": lane,
        "workbook_rows": len(parsed),
        "question_rows": len(question_rows or []),
        "matched_rows": len(matched_indices),
        "added_rows": len(additions),
        # Count each added row as a changed input so lifecycle callers that
        # only inspect ``changed_fields`` still trigger Pre regeneration.
        "changed_fields": len(concept_edits) + len(additions),
        "question_operations": len(question_operations),
        "round_recorded": True,
        "review": release_review.review_view(db, job, lane),
    }
